import { collection, addDoc, getDocs, doc, updateDoc, query, orderBy, limit, startAfter, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { db, auth } from '../services/firebase.js';
import { writeAdminLog } from '../services/firebase/adminLogRepository.js';

const NAME='problemReports',MAX_ID=128,MAX_DESC=2000;
const clean=v=>String(v??'').trim(),validId=id=>typeof id==='string'&&id.length>0&&id.length<=MAX_ID;
function validate(input={}){const data={sourceId:clean(input.sourceId),sourceTitle:clean(input.sourceTitle).slice(0,200),kind:clean(input.kind).slice(0,100),description:clean(input.description).slice(0,MAX_DESC)};if(!data.description)throw Error('REPORT_DESCRIPTION_REQUIRED');if(!data.kind)throw Error('REPORT_KIND_REQUIRED');return data;}
export async function createProblemReport(input){const data=validate(input);const user=auth.currentUser;if(!user)throw Error('REPORT_LOGIN_REQUIRED');const ref=await addDoc(collection(db,NAME),{...data,studentUid:user.uid,studentEmail:user.email||'',status:'open',createdAt:serverTimestamp()});await writeAdminLog({action:'create',collectionName:NAME,targetId:ref.id,details:{kind:data.kind,sourceId:data.sourceId,studentUid:user.uid}});return ref.id;}
export async function getMyProblemReports(pageSize=50){const user=auth.currentUser;if(!user)throw Error('REPORT_LOGIN_REQUIRED');const snap=await getDocs(query(collection(db,NAME),where('studentUid','==',user.uid),limit(Math.min(Math.max(Number(pageSize)||50,1),100))));const items=snap.docs.map(d=>({id:d.id,...d.data()}));items.sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));return items;}
export async function getProblemReports({pageSize=24,cursor=null,status=null}={}){const clauses=[];if(status)clauses.push(where('status','==',status));clauses.push(orderBy('createdAt','desc'));if(cursor)clauses.push(startAfter(cursor));clauses.push(limit(Math.min(Math.max(Number(pageSize)||24,1),50)));const snap=await getDocs(query(collection(db,NAME),...clauses));return{items:snap.docs.map(d=>({id:d.id,...d.data()})),nextCursor:snap.docs.at(-1)||null};}
export async function updateProblemReportStatus(id,status,note=''){if(!validId(id))throw Error('DOCUMENT_ID_INVALID');if(!['open','resolved','dismissed'].includes(status))throw Error('REPORT_STATUS_INVALID');await updateDoc(doc(db,NAME,id),{status,adminNote:clean(note).slice(0,1000),updatedAt:serverTimestamp()});await writeAdminLog({action:'update',collectionName:NAME,targetId:id,details:{status}});}
