import { auth, db } from '../services/firebase.js';
import { collection, doc, getDoc, getDocs, addDoc, setDoc, updateDoc, deleteDoc, query, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';

const SETS='studentFlashcardSets';
const SHARES='studentFlashcardShares';
const clean=v=>String(v??'').trim();
const uid=()=>auth.currentUser?.uid||null;
const safeId=id=>typeof id==='string'&&id.length>0&&id.length<=128;

function requireUser(){const id=uid();if(!id) throw Error('STUDENT_LOGIN_REQUIRED');return id}
function setData(input={}){const title=clean(input.title).slice(0,120);const description=clean(input.description).slice(0,500);if(!title)throw Error('FLASHCARD_SET_TITLE_REQUIRED');return {title,description,subjectId:clean(input.subjectId).slice(0,128),branchId:clean(input.branchId).slice(0,128)}}
function cardData(input={}){const question=clean(input.question).slice(0,4000),answer=clean(input.answer).slice(0,8000);if(!question)throw Error('FLASHCARD_QUESTION_REQUIRED');if(!answer)throw Error('FLASHCARD_ANSWER_REQUIRED');return {question,answer,tags:Array.isArray(input.tags)?input.tags.map(clean).filter(Boolean).slice(0,10):[],difficulty:clean(input.difficulty)||'medium'}}

export async function listMyFlashcardSets(){const id=requireUser();const snap=await getDocs(query(collection(db,SETS),where('ownerId','==',id)));return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.toMillis?.()||0)-(a.updatedAt?.toMillis?.()||0))}
export async function getMyFlashcardSet(setId){const id=requireUser();if(!safeId(setId))throw Error('DOCUMENT_ID_INVALID');const snap=await getDoc(doc(db,SETS,setId));if(!snap.exists()||snap.data().ownerId!==id)return null;return {id:snap.id,...snap.data()}}
export async function createMyFlashcardSet(input){const ownerId=requireUser();const data=setData(input);const ref=await addDoc(collection(db,SETS),{...data,ownerId,cardCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return ref.id}
export async function updateMyFlashcardSet(setId,input){const ownerId=requireUser();const current=await getMyFlashcardSet(setId);if(!current)throw Error('FLASHCARD_SET_NOT_FOUND');await updateDoc(doc(db,SETS,setId),{...setData(input),updatedAt:serverTimestamp(),ownerId});}
export async function deleteMyFlashcardSet(setId){const ownerId=requireUser();const current=await getMyFlashcardSet(setId);if(!current)throw Error('FLASHCARD_SET_NOT_FOUND');const cards=await getDocs(collection(db,SETS,setId,'cards'));await Promise.all(cards.docs.map(d=>deleteDoc(d.ref)));await deleteDoc(doc(db,SETS,setId));const share=await getDoc(doc(db,SHARES,setId));if(share.exists()&&share.data().ownerId===ownerId)await deleteDoc(share.ref)}
export async function listMyFlashcards(setId){const current=await getMyFlashcardSet(setId);if(!current)throw Error('FLASHCARD_SET_NOT_FOUND');const snap=await getDocs(collection(db,SETS,setId,'cards'));return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?.toMillis?.()||0)-(b.createdAt?.toMillis?.()||0))}
export async function createMyFlashcard(setId,input){const current=await getMyFlashcardSet(setId);if(!current)throw Error('FLASHCARD_SET_NOT_FOUND');const data=cardData(input);const ref=await addDoc(collection(db,SETS,setId,'cards'),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,SETS,setId),{cardCount:(current.cardCount||0)+1,updatedAt:serverTimestamp()});return ref.id}
export async function updateMyFlashcard(setId,cardId,input){const current=await getMyFlashcardSet(setId);if(!current||!safeId(cardId))throw Error('FLASHCARD_NOT_FOUND');await updateDoc(doc(db,SETS,setId,'cards',cardId),{...cardData(input),updatedAt:serverTimestamp()});await updateDoc(doc(db,SETS,setId),{updatedAt:serverTimestamp()})}
export async function deleteMyFlashcard(setId,cardId){const current=await getMyFlashcardSet(setId);if(!current||!safeId(cardId))throw Error('FLASHCARD_NOT_FOUND');await deleteDoc(doc(db,SETS,setId,'cards',cardId));await updateDoc(doc(db,SETS,setId),{cardCount:Math.max(0,(current.cardCount||1)-1),updatedAt:serverTimestamp()})}
export async function publishFlashcardShare(setId){const ownerId=requireUser();const current=await getMyFlashcardSet(setId);if(!current)throw Error('FLASHCARD_SET_NOT_FOUND');const cards=await listMyFlashcards(setId);const payload=cards.slice(0,150).map(c=>({question:c.question,answer:c.answer,tags:c.tags||[],difficulty:c.difficulty||'medium'}));await setDoc(doc(db,SHARES,setId),{ownerId,title:current.title,description:current.description||'',subjectId:current.subjectId||'',branchId:current.branchId||'',cards:payload,cardCount:payload.length,updatedAt:serverTimestamp()});return setId}
export async function getSharedFlashcardSet(setId){if(!safeId(setId))throw Error('DOCUMENT_ID_INVALID');const snap=await getDoc(doc(db,SHARES,setId));return snap.exists()?{id:snap.id,...snap.data()}:null}
export async function copySharedFlashcardSet(setId){const shared=await getSharedFlashcardSet(setId);if(!shared)throw Error('SHARED_SET_NOT_FOUND');const ownerId=requireUser();const newId=await createMyFlashcardSet({title:`${shared.title} (نسخة)`,description:`نسخة من مجموعة مشتركة: ${shared.description||''}`,subjectId:shared.subjectId||'',branchId:shared.branchId||''});for(const card of shared.cards||[])await addDoc(collection(db,SETS,newId,'cards'),{...card,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,SETS,newId),{cardCount:(shared.cards||[]).length,ownerId,updatedAt:serverTimestamp()});return newId}
