import { collection, doc, getDocs, addDoc, updateDoc, query, orderBy, limit, startAfter, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { db, auth } from '../services/firebase.js';
import { writeAdminLog } from '../services/firebase/adminLogRepository.js';

const NAME='suggestions',MAX_ID=128,MAX_TITLE=200,MAX_DESC=3000;
const clean=v=>String(v??'').trim(), validId=id=>typeof id==='string'&&id.length>0&&id.length<=MAX_ID;
function validate(input={}){const type=['resource','foundation','flashcard'].includes(input.contentType)?input.contentType:'resource';const data={title:clean(input.title).slice(0,MAX_TITLE),contentType:type,studentName:clean(input.studentName).slice(0,80),url:clean(input.url),branchId:clean(input.branchId),subjectId:clean(input.subjectId),level:clean(input.level),foundationType:clean(input.foundationType),type:clean(input.type),description:clean(input.description).slice(0,MAX_DESC),question:clean(input.question).slice(0,1000),answer:clean(input.answer).slice(0,3000),keywords:Array.isArray(input.keywords)?[...new Set(input.keywords.map(clean).filter(Boolean))].slice(0,30):[]};if(!data.title)throw Error('SUGGESTION_TITLE_REQUIRED');if(data.branchId.length===0||data.subjectId.length===0)throw Error('SUGGESTION_ACADEMIC_CONTEXT_REQUIRED');if(type==='flashcard'){if(!data.question||!data.answer)throw Error('FLASHCARD_SUGGESTION_CONTENT_REQUIRED')}else{let u;try{u=new URL(data.url)}catch{throw Error('SUGGESTION_URL_INVALID')}if(!['http:','https:'].includes(u.protocol))throw Error('SUGGESTION_URL_PROTOCOL')}return data;}
export async function createSuggestion(input){const data=validate(input);const user=auth.currentUser;if(!user && data.contentType!=='flashcard')throw Error('SUGGESTION_LOGIN_REQUIRED');const linked=user?{studentUid:user.uid,studentEmail:user.email||''}:{};const ref=await addDoc(collection(db,NAME),{...data,...linked,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(data.contentType!=='flashcard')await writeAdminLog({action:'create',collectionName:NAME,targetId:ref.id,details:{title:data.title,studentUid:user?.uid||null}});return ref.id;}
export async function getMySuggestions(pageSize=50){const user=auth.currentUser;if(!user)throw Error('SUGGESTION_LOGIN_REQUIRED');const snap=await getDocs(query(collection(db,NAME),where('studentUid','==',user.uid),limit(Math.min(Math.max(Number(pageSize)||50,1),100))));const items=snap.docs.map(d=>({id:d.id,...d.data()}));items.sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));return items;}
export async function getSuggestions({pageSize=24,cursor=null,status=null}={}){const clauses=[];if(status)clauses.push(where('status','==',status));clauses.push(orderBy('createdAt','desc'));if(cursor)clauses.push(startAfter(cursor));clauses.push(limit(Math.min(Math.max(Number(pageSize)||24,1),50)));const snap=await getDocs(query(collection(db,NAME),...clauses));return{items:snap.docs.map(d=>({id:d.id,...d.data()})),nextCursor:snap.docs.at(-1)||null};}
export async function updateSuggestionStatus(id,status,note=''){if(!validId(id))throw Error('DOCUMENT_ID_INVALID');if(!['pending','approved','rejected','archived'].includes(status))throw Error('SUGGESTION_STATUS_INVALID');await updateDoc(doc(db,NAME,id),{status,reviewerNote:clean(note).slice(0,1000),reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAdminLog({action:'update',collectionName:NAME,targetId:id,details:{status}});}
