const MAX_BODY=20000,MAX_CONTEXT=12000,MAX_QUESTION=3000;
const ALLOWED_ACTIONS=new Set(['ask','resource_search','classify','generate_questions','assess_level','study_plan']);
const FALLBACK_MODELS=['gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash','gemini-3.1-flash-lite'];
function allowedOrigins(env){return new Set(String(env.ALLOWED_ORIGINS||'https://pls455.github.io').split(',').map(v=>v.trim()).filter(Boolean))}
function cors(origin,allowed){return {'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':allowed.has(origin)?origin:'','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'}}
function json(data,status,headers){return new Response(JSON.stringify(data),{status,headers})}
function text(v,max){return String(v??'').trim().slice(0,max)}
function promptFor(action,data){
  const context=text(data.context,MAX_CONTEXT);
  if(action==='ask')return `أنت مساعد منهاج التعليمي. أجب بالعربية بوضوح ومن دون اختلاق. السؤال: ${text(data.question,MAX_QUESTION)}\nالسياق: ${context||'لا يوجد'}\nأعد JSON فقط: {"answer":"...","confidence":0,"usedContext":true,"sources":[]}`;
  if(action==='resource_search')return `أنت مساعد بحث لمصادر منصة منهاج. لديك قائمة مصادر مرشحة بصيغة JSON. اختر فقط المصادر التي تساعد فعليًا في طلب الطالب. لا تخترع أي معرفات أو روابط. طلب الطالب: ${text(data.question,MAX_QUESTION)}\nالمصادر المرشحة: ${text(data.resources,MAX_CONTEXT)}\nأعد JSON فقط بهذا الشكل: {"selectedIds":[],"reason":"..."}`;
  if(action==='classify')return `صنّف المصدر اعتمادًا على الأدلة فقط. الاسم: ${text(data.name,500)}\nالمسار: ${text(data.path,2000)}\nالوصف: ${text(data.description,2000)}\nأعد JSON فقط: {"branch":"غير محدد","subject":"غير محدد","category":"غير محدد","confidence":{"branch":0,"subject":0,"category":0,"overall":0},"evidence":[],"needsReview":true,"reason":"..."}`;
  if(action==='generate_questions')return `أنشئ أسئلة من المحتوى فقط. المادة: ${text(data.subject,300)}. العدد: ${Math.min(Math.max(Number(data.count)||10,1),20)}. الصعوبة: ${text(data.difficulty||'متوسط',30)}. المحتوى: ${context}\nأعد JSON فقط: {"questions":[{"question":"...","type":"mcq|true_false|short","options":[],"answer":"...","explanation":"..."}]}`;
  if(action==='assess_level')return `قيّم إجابات الطالب مقارنة بالأسئلة فقط. المادة: ${text(data.subject,300)}\nالأسئلة: ${text(data.questions,9000)}\nالإجابات: ${text(data.answers,9000)}\nأعد JSON فقط: {"score":0,"level":"مبتدئ","strengths":[],"weaknesses":[],"recommendations":[]}`;
  return `أنشئ خطة دراسة واقعية. المواد: ${text(data.subjects,2500)}. الأيام: ${Math.min(Math.max(Number(data.days)||7,1),30)}. ساعات يوميًا: ${Math.min(Math.max(Number(data.hoursPerDay)||2,.5),12)}. المستوى: ${text(data.level||'متوسط',100)}. الهدف: ${text(data.goal||'تحسين التحصيل',1000)}. أعد JSON فقط: {"summary":"...","days":[],"tips":[]}`
}
async function callModel(env,model,prompt){const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',signal:c.signal,headers:{'Content-Type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.2}})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d?.error?.message||`Gemini HTTP ${r.status}`);e.status=r.status;throw e}const value=d?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';if(!value)throw Object.assign(new Error('Empty Gemini response'),{status:502});try{return JSON.parse(value.replace(/^```json\s*|\s*```$/g,''))}catch{throw Object.assign(new Error('Invalid Gemini JSON'),{status:502})}}finally{clearTimeout(timer)}}
async function callGemini(env,prompt){if(!env.GEMINI_API_KEY){const e=new Error('AI service is not configured');e.status=503;throw e}const configured=String(env.GEMINI_MODEL||'').trim();const models=[configured,...FALLBACK_MODELS].filter((v,i,a)=>v&&a.indexOf(v)===i);let last;for(const model of models){try{return{result:await callModel(env,model,prompt),model}}catch(e){last=e;console.warn('[ai] model failed',model,e?.status,e?.message);if(![408,429,500,502,503,504].includes(e?.status)&&e?.name!=='AbortError')break}}throw last||new Error('AI request failed')}
export default{async fetch(request,env){const origin=request.headers.get('Origin')||'',allowed=allowedOrigins(env),headers=cors(origin,allowed);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(origin&&!allowed.has(origin))return json({ok:false,error:'Origin not allowed'},403,headers);if(request.method!=='POST'||new URL(request.url).pathname!=='/ai')return json({ok:false,error:'Not found'},404,headers);const length=Number(request.headers.get('content-length')||0);if(length>MAX_BODY)return json({ok:false,error:'Request too large'},413,headers);let data;try{data=await request.json()}catch{return json({ok:false,error:'Invalid JSON'},400,headers)}if(!data||typeof data!=='object'||Array.isArray(data)||!ALLOWED_ACTIONS.has(data.action))return json({ok:false,error:'Invalid action'},400,headers);if(['ask','resource_search'].includes(data.action)&&!text(data.question,MAX_QUESTION))return json({ok:false,error:'Question is required'},400,headers);try{if(!env.AI_RATE_LIMITER)return json({ok:false,error:'AI service is not configured'},503,headers);const rateKey=`ai:${request.headers.get('cf-connecting-ip')||'unknown'}:${origin||'no-origin'}`;const rate=await env.AI_RATE_LIMITER.limit({key:rateKey});if(!rate.success)return json({ok:false,error:'Too many AI requests. Please try again later.'},429,headers);const ai=await callGemini(env,promptFor(data.action,data));return json({ok:true,result:ai.result,ai:{provider:'Gemini',model:ai.model,action:data.action}},200,headers)}catch(e){console.error('[ai]',e);const status=e?.status>=500?e.status:502;return json({ok:false,error:e?.name==='AbortError'?'AI request timed out':e?.status===429?'Gemini busy or rate limited. Retrying another model did not succeed.':'AI request failed'},status,headers)}}}
