import { requireAuthenticatedAdmin, signOutUser } from '../services/firebase/auth.js';
import { permissions } from '../services/firebase/permissions.js';
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { db } from '../services/firebase.js';

const content=document.getElementById('adminContent');const identity=document.getElementById('adminIdentity');
function card(label,value){const article=document.createElement('article');article.className='admin-stat';const span=document.createElement('span');span.textContent=label;const strong=document.createElement('strong');strong.textContent=Number(value||0).toLocaleString('ar-EG');article.append(span,strong);return article}
function sectionLinks(admin){const nav=document.createElement('nav');nav.className='admin-nav-grid';nav.setAttribute('aria-label','أقسام الإدارة');const links=[];if(permissions.system(admin.role))links.push(['students.html','الطلاب المسجلون']);if(permissions.review(admin.role))links.push(['suggestions.html','الاقتراحات'],['problem-reports.html','بلاغات المشاكل']);if(permissions.content(admin.role))links.push(['resources.html','المصادر'],['solutions.html','الحلول'],['subjects.html','المواد'],['branches.html','الفروع'],['categories.html','التصنيفات'],['foundations.html','التأسيس'],['flashcards.html','البطاقات التعليمية'],['content-manager.html','مدير المحتوى'],['directorates.html','المديريات'],['schools.html','المدارس']);links.forEach(([href,label])=>{const a=document.createElement('a');a.className='admin-nav-card';a.href=href;a.textContent=label;nav.append(a)});return nav}
document.getElementById('logoutButton')?.addEventListener('click',async()=>{await signOutUser();location.href='index.html'});
async function load(){try{const{user,admin}=await requireAuthenticatedAdmin();identity.textContent=`${user.email||admin.email||'حساب الإدارة'} • ${admin.role||'reviewer'}`;const{count}=await import('../repositories/resourceRepository.js');const base=[count('branches',{active:true}),count('subjects',{active:true}),count('categories',{active:true}),count('resources',{active:true}),count('foundations',{active:true})];const extra=permissions.content(admin.role)?[getDocs(collection(db,'directorates')),getDocs(collection(db,'schools'))]:[Promise.resolve({size:0}),Promise.resolve({size:0})];const[branches,subjects,categories,resources,foundations,directorates,schools]=await Promise.all([...base,...extra]);const stats=document.createElement('div');stats.className='admin-stats';[['الطلاب المسجلون',permissions.system(admin.role)?(await getDocs(collection(db,'users'))).size:0],['المديريات',directorates.size],['المدارس',schools.size],['الفروع',branches],['المواد',subjects],['المصادر',resources],['التأسيس',foundations]].forEach(([label,value])=>stats.append(card(label,value)));content.replaceChildren(stats,sectionLinks(admin))}catch(error){console.error('[admin-dashboard]',error);const box=document.createElement('div');box.className='error-box';box.setAttribute('role','alert');box.textContent='تعذر التحقق من صلاحيات الإدارة أو تحميل الإحصائيات.';content.replaceChildren(box)}}
load();
