import { getPage, getAllSmall, saveResource, saveSourceRegistry, removeResource, count } from '../repositories/resourceRepository.js';
import { logAction } from './audit.js';
import { currentAdmin, hasRole, ROLES } from '../services/firebase/adminCore.js';
import { db } from '../services/firebase.js';
import { collection, deleteDoc, doc, addDoc, updateDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';

export const configs = {
  branches:{label:'الفروع',role:ROLES.SUPER_ADMIN,searchField:'name',fields:{name:'text',description:'textarea',icon:'text',order:'number',active:'checkbox'}},
  subjects:{label:'المواد',role:ROLES.CONTENT_ADMIN,searchField:'name',fields:{name:'text',branchIds:'ids',description:'textarea',icon:'text',order:'number',active:'checkbox'}},
  categories:{label:'التصنيفات',role:ROLES.SUPER_ADMIN,searchField:'name',fields:{name:'text',description:'textarea',icon:'text',order:'number',active:'checkbox'}},
  resources:{label:'المصادر',role:ROLES.CONTENT_ADMIN,searchField:'title',fields:{title:'text',url:'url',branchIds:'ids',subjectId:'text',categoryId:'text',type:'text',description:'textarea',author:'text',keywords:'ids',tags:'ids',order:'number',active:'checkbox'}},
  foundations:{label:'التأسيس',role:ROLES.CONTENT_ADMIN,searchField:'title',fields:{title:'text',url:'url',branchIds:'ids',subjectId:'text',level:'text',type:'text',description:'textarea',author:'text',keywords:'ids',order:'number',active:'checkbox'}},
  solutions:{label:'الحلول',role:ROLES.CONTENT_ADMIN,searchField:'title',fields:{title:'text',problem:'textarea',solution:'textarea',steps:'textarea',category:'text',keywords:'ids',status:'text',notes:'textarea',active:'checkbox'}},
  flashcards:{label:'البطاقات',role:ROLES.CONTENT_ADMIN,searchField:'question',fields:{question:'textarea',answer:'textarea',explanation:'textarea',branchId:'text',subjectId:'text',order:'number',active:'checkbox'}},
  templates:{label:'قوالب المصادر',role:ROLES.CONTENT_ADMIN,searchField:'name',fields:{name:'text',target:'text',description:'textarea',fields:'ids',instructions:'ids'}},
  sourceRegistry:{label:'سجل المصادر',role:ROLES.REVIEWER,writeRole:ROLES.REVIEWER,searchField:'name',orderField:'createdAt',fields:{sourceId:'text',name:'text',title:'text',url:'url',description:'textarea',status:'text',branchIds:'ids',subjectId:'text',categoryId:'text',keywords:'ids',tags:'ids',needsReview:'checkbox'}},
  suggestions:{label:'الاقتراحات',role:ROLES.REVIEWER,writeRole:ROLES.REVIEWER,searchField:'title',orderField:'createdAt',fields:{title:'text',url:'url',description:'textarea',contentType:'text',branchId:'text',subjectId:'text',level:'text',type:'text',status:'text',keywords:'ids',reviewerNote:'textarea'}},
  problemReports:{label:'البلاغات',role:ROLES.REVIEWER,writeRole:ROLES.REVIEWER,searchField:'sourceTitle',orderField:'createdAt',fields:{sourceId:'text',sourceTitle:'text',sourceUrl:'url',kind:'text',description:'textarea',status:'text',adminNote:'textarea'}},
  admins:{label:'المشرفون',role:ROLES.SUPER_ADMIN,searchField:'email',orderField:'createdAt',fields:{email:'email',role:'text',active:'checkbox'}},
  adminLogs:{label:'سجل الإدارة',role:ROLES.SUPER_ADMIN,readOnly:true,searchField:'collection',orderField:'createdAt',fields:{action:'text',collection:'text',targetId:'text',details:'textarea',adminUid:'text',adminEmail:'email',role:'text'}}
};

const errorMap={RESOURCE_TITLE_REQUIRED:'يرجى إدخال عنوان المصدر.',RESOURCE_URL_REQUIRED:'يرجى إدخال رابط المصدر.',RESOURCE_URL_INVALID:'رابط المصدر غير صالح.',RESOURCE_URL_PROTOCOL:'رابط المصدر يجب أن يبدأ بـ http أو https.',RESOURCE_BRANCH_REQUIRED:'يرجى اختيار فرع واحد على الأقل.',RESOURCE_SUBJECT_REQUIRED:'يرجى اختيار المادة.',RESOURCE_URL_DUPLICATE:'هذا الرابط موجود مسبقًا.',RESOURCE_NOT_FOUND:'المصدر غير موجود.'};
export function friendlyError(e){const key=e?.message||e?.code||'';return errorMap[key]||key||'تعذر تنفيذ العملية، حاول مرة أخرى.'}
let state={collection:'branches',cursor:null,admin:null};
export function setAdmin(a){state.admin=a} export function getAdmin(){return state.admin}
export function allowed(c){return !!state.admin&&hasRole(state.admin.role,configs[c]?.role||ROLES.REVIEWER)}
export function canWrite(c){const cfg=configs[c];return allowed(c)&&!cfg.readOnly&&hasRole(state.admin.role,cfg.writeRole||cfg.role)}
export async function loadPage(c,filters={}){const cfg=adminApiConfig(c);if(!filters.search&&['branches','subjects','categories'].includes(c)){const rows=await getAllSmall(c,100,true);return{rows,nextCursor:null,hasMore:false};}return getPage(c,{...filters,searchField:cfg.searchField,orderField:cfg.orderField},20,state.cursor)}
function adminApiConfig(c){return configs[c]||{label:c,role:ROLES.REVIEWER,searchField:'name'};}
export async function persist(c,id,payload){const actor=await currentAdmin();if(!actor||!hasRole(actor.role,configs[c]?.role||ROLES.REVIEWER)||configs[c]?.readOnly)throw Error('ليس لديك صلاحية للكتابة');const next={...payload};if(['branches','subjects','categories'].includes(c)&&!next.stableId&&next.name){next.stableId=String(next.name).trim().toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-|-$/g,'')||`item-${Date.now()}`;}let saved;if(c==='resources'){saved=await saveResource(id||null,next);return saved;}if(c==='sourceRegistry'){saved=await saveSourceRegistry(id||null,next);}else if(id){await updateDoc(doc(db,c,id),{...next,updatedAt:serverTimestamp()});saved=id;}else{const r=await addDoc(collection(db,c),{...next,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});saved=r.id;}try{await logAction(actor,id?'update':'create',c,saved,next.title||next.name||next.question||next.email||next.sourceId||'')}catch(error){console.warn('[admin.persist.audit]',error)}return saved}
export async function erase(c,id){const actor=await currentAdmin();const cfg=configs[c];if(!actor||!cfg||cfg.readOnly||!hasRole(actor.role,cfg.writeRole||cfg.role))throw Error('ليس لديك صلاحية للحذف');if(!id||typeof id!=='string'||id.length>128)throw Error('معرّف العنصر غير صالح');if(c==='resources'){await removeResource(id);return;}await deleteDoc(doc(db,c,id));try{await logAction(actor,'delete',c,id,'')}catch(error){console.warn('[admin.erase.audit]',error)}}
export async function stats(){const names=['branches','subjects','categories','resources','foundations','suggestions','problemReports'];const out={};await Promise.all(names.map(async n=>{const f=n==='suggestions'?{status:'pending'}:n==='problemReports'?{status:'open'}:{};try{out[n]=await count(n,f)}catch(e){console.warn('[admin.stats]',n,e);out[n]=0}}));return out}
export function toPayload(c,form){const p={};for(const[key,type]of Object.entries(configs[c].fields)){const el=form.elements[key];if(!el)continue;if(type==='checkbox')p[key]=el.checked;else if(type==='number'){const n=Number(el.value);if(!Number.isInteger(n)||n<0)throw Error('الترتيب يجب أن يكون رقمًا صحيحًا غير سالب');p[key]=n}else if(type==='ids')p[key]=el.multiple?[...el.selectedOptions].map(o=>o.value).filter(Boolean):el.value.split(',').map(x=>x.trim()).filter(Boolean);else{const value=el.value.trim();if(key==='url'&&value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol))throw 0}catch{throw Error('الرابط يجب أن يبدأ بـ http أو https')}}p[key]=value;}}if(c==='flashcards'){if(!p.question||p.question.length<2)throw Error('السؤال مطلوب ويجب أن يحتوي على حرفين على الأقل');if(!p.answer)throw Error('الإجابة مطلوبة');if(p.question.length>5000||p.answer.length>10000||(p.explanation||'').length>10000)throw Error('محتوى البطاقة أطول من الحد المسموح');}if(c==='suggestions'){if(!p.title||p.title.length<3)throw Error('عنوان الاقتراح مطلوب');if((p.description||'').length>5000)throw Error('الاقتراح طويل جدًا')}if(c==='problemReports'){if(!p.description||p.description.length<5)throw Error('وصف البلاغ مطلوب');if(p.description.length>2000)throw Error('البلاغ طويل جدًا')}if(c==='templates'){if(!p.name||p.name.length<2)throw Error('اسم القالب مطلوب');if(!p.target)throw Error('يجب تحديد هدف القالب');if(p.fields.length>100)throw Error('عدد حقول القالب كبير جدًا');if(p.instructions.length>100)throw Error('عدد تعليمات القالب كبير جدًا')}if(c==='sourceRegistry'){if(!p.sourceId)p.sourceId='source-'+Date.now();if(!p.name&&!p.title)throw Error('اسم المصدر مطلوب');if(p.status&&!['pending_review','published','rejected','approved','pending','indexed','ready','error','archived'].includes(p.status))throw Error('حالة المصدر غير صالحة')}return p}
export function initialValue(type,v){if(type==='checkbox')return!!v;if(type==='ids')return Array.isArray(v)?v.join(', '):String(v||'');return String(v??'');}
export{state};
