import { db } from '../services/firebase.js';
import { collection, getDocs, query, limit, addDoc, updateDoc, doc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { getAdmin } from './data.js';

const DRIVE_FOLDER='application/vnd.google-apps.folder';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let refs={branches:[],subjects:[],categories:[]},files=[];
const keys={drive:()=>localStorage.getItem('minhaj_drive_api_key')||'',gemini:()=>localStorage.getItem('minhaj_gemini_api_key')||''};
const msg=(text,error=false)=>{const e=$('driveMsg');if(e){e.textContent=text||'';e.className=text?`message ${error?'error':'success'}`:'message'}};
async function getRef(name){return (await getDocs(query(collection(db,name),limit(2000)))).docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false)}
async function loadRefs(){[refs.branches,refs.subjects,refs.categories]=await Promise.all([getRef('branches'),getRef('subjects'),getRef('categories')])}
function parseDriveUrl(value){try{const u=new URL(String(value||'').trim());if(!/drive\.google\.com$/i.test(u.hostname))return null;let m=u.pathname.match(/\/file\/d\/([\w-]+)/);if(m)return{id:m[1],kind:'file'};m=u.pathname.match(/\/folders\/([\w-]+)/);if(m)return{id:m[1],kind:'folder'};const id=u.searchParams.get('id');return id?{id,kind:u.pathname.includes('folder')?'folder':'file'}:null}catch{return null}}
async function drive(path,params={}){const key=keys.drive();if(!key)throw Error('أدخل مفتاح Google Drive API أولًا.');const u=new URL(`https://www.googleapis.com/drive/v3/${path}`);Object.entries({...params,key}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||`Drive API ${r.status}`);return d}
async function inspect(value){const p=parseDriveUrl(value);if(!p)throw Error('رابط Google Drive غير صالح.');if(p.kind==='file'){try{const x=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,size,modifiedTime,webViewLink,description,trashed'});if(x.trashed)throw Error('العنصر موجود في سلة المهملات.');return[x]}catch(e){if(!keys.drive())return[{id:p.id,name:'ملف Google Drive',mimeType:'application/octet-stream',webViewLink:`https://drive.google.com/file/d/${encodeURIComponent(p.id)}/view`}];throw e}}
const root=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,trashed'});if(root.trashed)throw Error('المجلد موجود في سلة المهملات.');if(root.mimeType!==DRIVE_FOLDER)return[root];const out=[];async function walk(parent,path,depth=0){if(depth>12||out.length>=2000)return;let token='';do{const d=await drive('files',{q:`'${parent}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,size,modifiedTime,webViewLink,description,trashed)',pageSize:'1000',orderBy:'folder,name',...(token?{pageToken:token}:{})});for(const x of d.files||[]){if(x.mimeType===DRIVE_FOLDER)await walk(x.id,[...path,x.name],depth+1);else out.push({...x,path:[...path,x.name].join(' / ')})}token=d.nextPageToken||''}while(token&&out.length<2000)}await walk(root.id,[root.name]);return out}
function aiPrompt(items){return `أنت مساعد تصنيف مصادر لمنصة تعليمية عربية. اختر فقط IDs الموجودة في القوائم التالية، ولا تخترع أي معرف. لكل ملف أرجع JSON فيه fileId, suggestedTitle, branchIds, subjectId, categoryId, confidence, needsReview, reason. إذا لم تكن متأكدًا اترك الحقل فارغًا واجعل needsReview=true.\nالفروع: ${JSON.stringify(refs.branches.map(x=>({id:x.id,name:x.name,stableId:x.stableId||''})))}\nالمواد: ${JSON.stringify(refs.subjects.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',branchIds:x.branchIds||[]})))}\nالتصنيفات: ${JSON.stringify(refs.categories.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',subjectId:x.subjectId||'',branchIds:x.branchIds||[]})))}\nالملفات: ${JSON.stringify(items.map(x=>({fileId:x.id,name:x.name,mimeType:x.mimeType,path:x.path||'',description:x.description||''})))}\nأعد مصفوفة JSON فقط.`}
async function classify(items){const key=keys.gemini();if(!key)return items.map(x=>({fileId:x.id,suggestedTitle:x.name,branchIds:[],subjectId:'',categoryId:'',confidence:0,needsReview:true,reason:'لم يتم إدخال مفتاح Gemini.'}));const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:aiPrompt(items)}]}],generationConfig:{response_mime_type:'application/json',response_schema:{type:'ARRAY',items:{type:'OBJECT',properties:{fileId:{type:'STRING'},suggestedTitle:{type:'STRING'},branchIds:{type:'ARRAY',items:{type:'STRING'}},subjectId:{type:'STRING'},categoryId:{type:'STRING'},confidence:{type:'NUMBER'},needsReview:{type:'BOOLEAN'},reason:{type:'STRING'}},required:['fileId','suggestedTitle','branchIds','subjectId','categoryId','confidence','needsReview','reason']}}}})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||'تعذر الاتصال بـ Gemini.');const text=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'[]';return JSON.parse(text)}
function options(rows,selected=''){return `<option value="">غير محدد</option>${rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(selected)?'selected':''}>${esc(x.name)}</option>`).join('')}`}
function renderRows(results){const map=new Map(results.map(x=>[String(x.fileId),x]));$('driveResults').innerHTML=files.map((f,i)=>{const a=map.get(String(f.id))||{suggestedTitle:f.name,branchIds:[],subjectId:'',categoryId:'',confidence:0,needsReview:true,reason:'لا يوجد تحليل'};return `<article class="drive-review-card"><label class="check"><input type="checkbox" data-drive-select="${i}" checked> ${esc(f.name)}</label><small>${esc(f.path||f.mimeType||'')}</small><label>العنوان<input data-drive-title="${i}" value="${esc(a.suggestedTitle||f.name)}"></label><label>المادة<select data-drive-subject="${i}">${options(refs.subjects,a.subjectId)}</select></label><label>التصنيف<select data-drive-category="${i}">${options(refs.categories,a.categoryId)}</select></label><div class="drive-branches"><strong>الفروع</strong>${refs.branches.map(b=>`<label class="check"><input type="checkbox" data-drive-branch="${i}" value="${esc(b.id)}" ${(a.branchIds||[]).map(String).includes(String(b.id))?'checked':''}> ${esc(b.name)}</label>`).join('')}</div><small>الثقة: ${Number(a.confidence)||0}% ${a.reason?`• ${esc(a.reason)}`:''}</small></article>`}).join('')||'<div class="empty">لا توجد ملفات.</div>'}
async function addSelected(){const admin=getAdmin();if(!admin)throw Error('انتهت جلسة الإدارة.');const selected=[...document.querySelectorAll('[data-drive-select]:checked')].map(el=>Number(el.getAttribute('data-drive-select'))).filter(i=>Number.isInteger(i)&&i>=0&&i<files.length);if(!selected.length){msg('لم يتم تحديد أي مصدر للإضافة.',true);return}let added=0;for(const i of selected){const f=files[i],title=$(`[data-drive-title="${i}"]`)?.value.trim()||f.name,subjectId=$(`[data-drive-subject="${i}"]`)?.value||'',categoryId=$(`[data-drive-category="${i}"]`)?.value||'',branchIds=[...document.querySelectorAll(`[data-drive-branch="${i}"]:checked`)].map(x=>x.value);await addDoc(collection(db,'sourceRegistry'),{sourceId:f.id,name:title,title,url:f.webViewLink||`https://drive.google.com/file/d/${encodeURIComponent(f.id)}/view`,originalTitle:f.name,path:f.path||'',mimeType:f.mimeType||'',branchIds,subjectId,categoryId,status:'pending_review',needsReview:true,active:false,provider:'google_drive',createdBy:admin.uid||'',createdByEmail:admin.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});added++}msg(`تمت إضافة ${added} مصدر إلى سجل المراجعة.`)}
export async function renderDrive(root){root.innerHTML=`<div class="section-head"><div><h2>مصادر Google Drive</h2><p class="muted">افحص ملفات Drive، صنّفها بمساعدة Gemini، ثم أرسلها للمراجعة قبل النشر.</p></div></div><div class="form-card"><label>رابط ملف أو مجلد Google Drive<input id="driveUrl" type="url" placeholder="https://drive.google.com/drive/folders/..." autocomplete="off"></label><label>مفتاح Google Drive API<input id="driveKey" type="password" placeholder="يُحفظ على هذا الجهاز فقط" autocomplete="off"></label><label>مفتاح Gemini API<input id="geminiKey" type="password" placeholder="يُحفظ على هذا الجهاز فقط" autocomplete="off"></label><div class="actions"><button id="saveDriveKeys" class="button">حفظ المفاتيح</button><button id="inspectDrive" class="button primary">فحص Drive وتصنيف بالذكاء الاصطناعي</button></div><p id="driveMsg" class="message"></p></div><div id="driveResults" class="drive-items"></div><div class="form-card"><button id="addDriveSources" class="button primary">إضافة المحدد إلى المراجعة</button></div>`;await loadRefs();$('driveKey').value=keys.drive();$('geminiKey').value=keys.gemini();$('saveDriveKeys').onclick=()=>{localStorage.setItem('minhaj_drive_api_key',$('driveKey').value.trim());localStorage.setItem('minhaj_gemini_api_key',$('geminiKey').value.trim());msg('تم حفظ المفاتيح على هذا الجهاز فقط.')};$('inspectDrive').onclick=async()=>{try{$('inspectDrive').disabled=true;msg('جاري فحص Drive...');files=await inspect($('driveUrl').value);msg(`تم العثور على ${files.length} ملف. جاري التصنيف...`);const results=await classify(files);renderRows(results);msg('اكتمل الفحص والتصنيف. لم يتم نشر أي مصدر.')}catch(e){console.error('[admin.drive]',e);msg(e.message||'تعذر فحص Drive.',true)}finally{$('inspectDrive').disabled=false}};$('addDriveSources').onclick=async()=>{try{$('addDriveSources').disabled=true;await addSelected()}catch(e){console.error('[admin.drive.add]',e);msg(e.message||'تعذر إضافة المصادر للمراجعة.',true)}finally{$('addDriveSources').disabled=false}}}
