import { db } from '../services/firebase.js';
import { collection, getDocs, query, limit, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { getAdmin } from './data.js';

const DRIVE_FOLDER='application/vnd.google-apps.folder';
const DRIVE_DOC='application/vnd.google-apps.document';
const DRIVE_SHEET='application/vnd.google-apps.spreadsheet';
const GEMINI_TIMEOUT_MS=12000;
const CONTENT_LIMIT=12000;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let refs={branches:[],subjects:[],categories:[]},files=[];
const keys={drive:()=>localStorage.getItem('minhaj_drive_api_key')||'',gemini:()=>localStorage.getItem('minhaj_gemini_api_key')||''};
const msg=(text,error=false)=>{const e=$('driveMsg');if(e){e.textContent=text||'';e.className=text?`message ${error?'error':'success'}`:'message'}};
async function getRef(name){return (await getDocs(query(collection(db,name),limit(2000)))).docs.map(d=>({id:d.id,...d.data()}))}
async function loadRefs(){[refs.branches,refs.subjects,refs.categories]=await Promise.all([getRef('branches'),getRef('subjects'),getRef('categories')])}
function parseDriveUrl(value){try{const u=new URL(String(value||'').trim());if(!/drive\\.google\\.com$/i.test(u.hostname))return null;let m=u.pathname.match(/\\/file\\/d\\/([\\w-]+)/);if(m)return{id:m[1],kind:'file'};m=u.pathname.match(/\\/folders\\/([\\w-]+)/);if(m)return{id:m[1],kind:'folder'};const id=u.searchParams.get('id');return id?{id,kind:u.pathname.includes('folder')?'folder':'file'}:null}catch{return null}}
async function drive(path,params={}){const key=keys.drive();if(!key)throw Error('أدخل مفتاح Google Drive API أولًا.');const u=new URL(`https://www.googleapis.com/drive/v3/${path}`);Object.entries({...params,key}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||`Drive API ${r.status}`);return d}
async function driveRaw(path,params={}){const key=keys.drive();if(!key)throw Error('أدخل مفتاح Google Drive API أولًا.');const u=new URL(`https://www.googleapis.com/drive/v3/${path}`);Object.entries({...params,key}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw Error(`Drive content ${r.status}`);return (await r.text()).slice(0,CONTENT_LIMIT)}
async function readDriveContent(file){const mime=String(file?.mimeType||'');try{if(mime===DRIVE_DOC)return await driveRaw(`files/${encodeURIComponent(file.id)}/export`,{mimeType:'text/plain'});if(mime===DRIVE_SHEET)return await driveRaw(`files/${encodeURIComponent(file.id)}/export`,{mimeType:'text/csv'});if(mime.startsWith('text/')||/^(application\\/(json|xml|csv|javascript)|text\\/csv)$/i.test(mime))return await driveRaw(`files/${encodeURIComponent(file.id)}`,{alt:'media'});return ''}catch(e){console.warn('[admin.drive] content extraction skipped',file?.name,e);return ''}}
async function enrichDriveContent(items){const results=await Promise.allSettled(items.map(readDriveContent));return items.map((x,i)=>({...x,content:results[i].status==='fulfilled'?results[i].value:''}))}
async function inspect(value){const p=parseDriveUrl(value);if(!p)throw Error('رابط Google Drive غير صالح.');if(p.kind==='file'){const x=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,size,modifiedTime,webViewLink,description,trashed'});if(x.trashed)throw Error('العنصر موجود في سلة المهملات.');return[x]}
const root=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,trashed'});if(root.trashed)throw Error('المجلد موجود في سلة المهملات.');if(root.mimeType!==DRIVE_FOLDER)return[root];const out=[];async function walk(parent,path,depth=0){if(depth>12||out.length>=2000)return;let token='';do{const d=await drive('files',{q:`'${parent}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,size,modifiedTime,webViewLink,description,trashed)',pageSize:'1000',orderBy:'folder,name',...(token?{pageToken:token}:{})});for(const x of d.files||[]){if(x.mimeType===DRIVE_FOLDER)await walk(x.id,[...path,x.name],depth+1);else out.push({...x,path:[...path,x.name].join(' / ')})}token=d.nextPageToken||''}while(token&&out.length<2000)}await walk(root.id,[root.name]);return out}
function aiPrompt(items){return `أنت مساعد تصنيف مصادر لمنصة تعليمية عربية. اختر فقط IDs الموجودة في القوائم التالية، ولا تخترع أي معرف. لكل ملف أرجع JSON فيه fileId, suggestedTitle, branchIds, subjectId, categoryId, confidence, needsReview, reason. استخدم قيمة id نفسها عند اختيار أي عنصر، وليس stableId. إذا لم تكن متأكدًا اترك الحقل فارغًا واجعل needsReview=true.\\nالفروع: ${JSON.stringify(refs.branches.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',active:x.active!==false})))}\\nالمواد: ${JSON.stringify(refs.subjects.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',branchIds:x.branchIds||[],active:x.active!==false})))}\\nالتصنيفات: ${JSON.stringify(refs.categories.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',subjectId:x.subjectId||'',branchIds:x.branchIds||[],active:x.active!==false})))}\\nالملفات: ${JSON.stringify(items.map(x=>({fileId:x.id,name:x.name,mimeType:x.mimeType,path:x.path||'',description:x.description||'',content:(x.content||'').slice(0,CONTENT_LIMIT)})))}\\nأعد مصفوفة JSON فقط.`}
function resolveId(value,rows){const s=String(value??'').trim();if(!s)return'';return rows.find(x=>String(x.id)===s)?.id||rows.find(x=>String(x.stableId||'')===s)?.id||rows.find(x=>String(x.name||'').trim()===s)?.id||''}
function normalizeAnalysis(a){return {...a,branchIds:[...(a?.branchIds||[])].map(v=>resolveId(v,refs.branches)).filter(Boolean),subjectId:resolveId(a?.subjectId,refs.subjects),categoryId:resolveId(a?.categoryId,refs.categories)}}
function fallbackClassify(items,reason='تعذر استخدام Gemini'){return items.map(x=>{const hay=`${x.name||''} ${x.path||''} ${x.description||''} ${x.content||''}`.toLowerCase();const subject=refs.subjects.map(s=>({s,score:scoreMatch(hay,s)})).sort((a,b)=>b.score-a.score)[0];const category=refs.categories.map(c=>({c,score:scoreMatch(hay,c)})).sort((a,b)=>b.score-a.score)[0];const branchIds=refs.branches.filter(b=>scoreMatch(hay,b)>=0.65).map(b=>b.id);const sid=subject?.score>=0.65?subject.s.id:'';const cid=category?.score>=0.65?category.c.id:'';const confidence=Math.round(Math.max(subject?.score||0,category?.score||0)*100);return {fileId:x.id,suggestedTitle:x.name||'مصدر Drive',branchIds,subjectId:sid,categoryId:cid,confidence,needsReview:true,reason:`${reason}. تم استخدام اسم الملف والمسار والوصف ومحتوى الملف المتاح مباشرة من Drive.`}})}
function scoreMatch(text,row){const terms=String(row?.name||'').toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>=2);if(!terms.length)return 0;const hits=terms.filter(t=>text.includes(t)).length;return hits/terms.length}
async function classify(items){const key=keys.gemini();if(!key)return fallbackClassify(items,'لم يتم إدخال مفتاح Gemini');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),GEMINI_TIMEOUT_MS);try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},signal:controller.signal,body:JSON.stringify({contents:[{parts:[{text:aiPrompt(items)}]}],generationConfig:{response_mime_type:'application/json',response_schema:{type:'ARRAY',items:{type:'OBJECT',properties:{fileId:{type:'STRING'},suggestedTitle:{type:'STRING'},branchIds:{type:'ARRAY',items:{type:'STRING'}},subjectId:{type:'STRING'},categoryId:{type:'STRING'},confidence:{type:'NUMBER'},needsReview:{type:'BOOLEAN'},reason:{type:'STRING'}},required:['fileId','suggestedTitle','branchIds','subjectId','categoryId','confidence','needsReview','reason']}}}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||`Gemini API ${r.status}`);const text=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'[]';return JSON.parse(text).map(normalizeAnalysis)}catch(e){console.warn('[admin.drive] Gemini unavailable, using Drive fallback',e);return fallbackClassify(items,e?.name==='AbortError'?'انتهت مهلة Gemini':(e?.message||'تعذر الاتصال بـ Gemini'))}finally{clearTimeout(timer)}}
function options(rows,selected=''){return `<option value="">غير محدد</option>${rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(selected)?'selected':''}>${esc(x.name)}${x.active===false?' (غير نشط)':''}</option>`).join('')}`}
function renderRows(results){const map=new Map(results.map(normalizeAnalysis).map(x=>[String(x.fileId),x]));$('driveResults').innerHTML=files.map((f,i)=>{const a=map.get(String(f.id))||{suggestedTitle:f.name,branchIds:[],subjectId:'',categoryId:'',confidence:0,needsReview:true,reason:'لا يوجد تحليل'};return `<article class="drive-review-card"><label class="check"><input type="checkbox" data-drive-select="${i}" checked> ${esc(f.name)}</label><small>${esc(f.path||f.mimeType||'')}</small><label>العنوان<input data-drive-title="${i}" value="${esc(a.suggestedTitle||f.name)}"></label><label>المادة<select data-drive-subject="${i}">${options(refs.subjects,a.subjectId)}</select></label><label>التصنيف<select data-drive-category="${i}">${options(refs.categories,a.categoryId)}</select></label><div class="drive-branches"><strong>الفروع</strong>${refs.branches.map(b=>`<label class="check"><input type="checkbox" data-drive-branch="${i}" value="${esc(b.id)}" ${(a.branchIds||[]).map(String).includes(String(b.id))?'checked':''}> ${esc(b.name)}${b.active===false?' (غير نشط)':''}</label>`).join('')}</div><small>الثقة: ${Number(a.confidence)||0}% ${a.reason?`• ${esc(a.reason)}`:''}</small></article>`}).join('')||'<div class="empty">لا توجد ملفات.</div>'}
async function addSelected(){const admin=getAdmin();if(!admin)throw Error('انتهت جلسة الإدارة.');const selected=[...document.querySelectorAll('[data-drive-select]:checked')].map(el=>Number(el.getAttribute('data-drive-select'))).filter(i=>Number.isInteger(i)&&i>=0&&i<files.length);if(!selected.length){msg('لم يتم تحديد أي مصدر للإضافة.',true);return}let added=0,skipped=0;for(const i of selected){const f=files[i],title=$(`[data-drive-title="${i}"]`)?.value.trim()||f.name,subjectId=resolveId($(`[data-drive-subject="${i}"]`)?.value,refs.subjects),categoryId=resolveId($(`[data-drive-category="${i}"]`)?.value,refs.categories),branchIds=[...document.querySelectorAll(`[data-drive-branch="${i}"]:checked`)].map(x=>resolveId(x.value,refs.branches)).filter(Boolean);if(!subjectId||!branchIds.length){skipped++;continue}await addDoc(collection(db,'sourceRegistry'),{sourceId:f.id,name:title,title,url:f.webViewLink||`https://drive.google.com/file/d/${encodeURIComponent(f.id)}/view`,originalTitle:f.name,path:f.path||'',mimeType:f.mimeType||'',branchIds,subjectId,categoryId,keywords:[],tags:[],status:'pending_review',needsReview:true,active:false,provider:'google_drive',createdBy:admin.uid||'',createdByEmail:admin.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});added++}msg(skipped?`تمت إضافة ${added} مصدر إلى سجل المراجعة، وتخطي ${skipped} مصدر لعدم اكتمال الفرع أو المادة.`:`تمت إضافة ${added} مصدر إلى سجل المراجعة.`)}
export async function renderDrive(root){root.innerHTML=`<div class="section-head"><div><h2>مصادر Google Drive</h2><p class="muted">افحص ملفات Drive، صنّفها بمساعدة Gemini، ثم أرسلها للمراجعة قبل النشر.</p></div></div><div class="form-card"><label>رابط ملف أو مجلد Google Drive<input id="driveUrl" type="url" placeholder="https://drive.google.com/drive/folders/..." autocomplete="off"></label><label>مفتاح Google Drive API<input id="driveKey" type="password" placeholder="يُحفظ على هذا الجهاز فقط" autocomplete="off"></label><label>مفتاح Gemini API<input id="geminiKey" type="password" placeholder="يُحفظ على هذا الجهاز فقط" autocomplete="off"></label><div class="actions"><button id="saveDriveKeys" class="button">حفظ المفاتيح</button><button id="inspectDrive" class="button primary">فحص Drive وتصنيف بالذكاء الاصطناعي</button></div><p id="driveMsg" class="message"></p></div><div id="driveResults" class="drive-items"></div><div class="form-card"><button id="addDriveSources" class="button primary">إضافة المحدد إلى المراجعة</button></div>`;await loadRefs();$('driveKey').value=keys.drive();$('geminiKey').value=keys.gemini();$('saveDriveKeys').onclick=()=>{localStorage.setItem('minhaj_drive_api_key',$('driveKey').value.trim());localStorage.setItem('minhaj_gemini_api_key',$('geminiKey').value.trim());msg('تم حفظ المفاتيح على هذا الجهاز فقط.')};$('inspectDrive').onclick=async()=>{try{$('inspectDrive').disabled=true;msg('جاري فحص Drive...');files=await inspect($('driveUrl').value);msg(`تم العثور على ${files.length} ملف. جاري قراءة المحتوى المتاح من Drive...`);files=await enrichDriveContent(files);msg(`تم العثور على ${files.length} ملف. جاري التصنيف...`);const results=await classify(files);renderRows(results);const usedFallback=results.some(x=>String(x.reason||'').includes('تم استخدام اسم الملف والمسار والوصف ومحتوى الملف المتاح مباشرة من Drive'));msg(usedFallback?'Gemini غير متاح حاليًا، لكن تم تحليل المصادر من بيانات ومحتوى Drive المتاح وإكمال العملية.':'اكتمل الفحص والتصنيف. لم يتم نشر أي مصدر.')}catch(e){console.error('[admin.drive]',e);msg(e.message||'تعذر فحص Drive.',true)}finally{$('inspectDrive').disabled=false}};$('addDriveSources').onclick=async()=>{try{$('addDriveSources').disabled=true;await addSelected()}catch(e){console.error('[admin.drive.add]',e);msg(e.message||'تعذر إضافة المصادر للمراجعة.',true)}finally{$('addDriveSources').disabled=false}}}
