import { requireAdmin, ROLES } from '../services/firebase/adminCore.js';
import { getProblemReports, updateProblemReportStatus } from '../repositories/problemReportRepository.js';
import { renderNavbar, renderFooter } from '../components/layout.js';
await requireAdmin(ROLES.CONTENT_ADMIN); renderNavbar(); renderFooter();
const $=id=>document.getElementById(id); let cursor=null,loading=false,busy=false;
function state(text,error=false){const el=document.createElement('div');el.className=error?'message error':'message';el.textContent=text;el.setAttribute('role',error?'alert':'status');return el}
function render(items){const root=$('report-list');root.replaceChildren();if(!items.length){root.append(state('لا توجد بلاغات.'));return}for(const item of items){const card=document.createElement('article');card.className='card admin-row';const body=document.createElement('div');const title=document.createElement('h3');title.textContent=item.sourceTitle||item.kind||'بلاغ';const desc=document.createElement('p');desc.textContent=item.description||'';const status=document.createElement('small');status.textContent=item.status||'open';body.append(title,desc,status);const actions=document.createElement('div');actions.className='actions';if(item.status!=='resolved'){const b=document.createElement('button');b.className='button';b.type='button';b.textContent='تم الحل';b.addEventListener('click',()=>change(item,'resolved'));actions.append(b)}if(item.status!=='dismissed'){const b=document.createElement('button');b.className='button danger';b.type='button';b.textContent='استبعاد';b.addEventListener('click',()=>change(item,'dismissed'));actions.append(b)}card.append(body,actions);root.append(card)}}
async function load(){if(loading)return;loading=true;$('message').replaceChildren(state('جاري التحميل...'));try{const r=await getProblemReports({pageSize:24,cursor,status:$('status').value||null});render(r.items);cursor=r.nextCursor;const p=$('pagination');p.replaceChildren();if(r.nextCursor){const b=document.createElement('button');b.className='button';b.type='button';b.textContent='التالي';b.addEventListener('click',load);p.append(b)}$('message').replaceChildren()}catch(e){console.error('[admin/problem-reports.load]',e);$('message').replaceChildren(state('تعذر تحميل البلاغات.',true))}finally{loading=false}}
async function change(item,status){if(busy||!confirm(`تأكيد تغيير حالة البلاغ إلى «${status}»؟`))return;busy=true;try{const note=prompt('ملاحظة إدارية (اختياري):','');if(note===null)return;await updateProblemReportStatus(item.id,status,note);cursor=null;await load()}catch(e){console.error('[admin/problem-reports.update]',e);alert('تعذر تحديث البلاغ.')}finally{busy=false}}
$('status').addEventListener('change',()=>{cursor=null;load()});$('reload').addEventListener('click',()=>{cursor=null;load()});await load();
