import { renderNavbar, renderFooter } from "../components/layout.js";
import { requireAuthenticatedAdmin, getCurrentAdmin } from "../services/firebase/auth.js";
import { resourceRepository, getAllSmall } from "../repositories/resourceRepository.js";
import { ROLES, hasRole } from "../core/constants.js";
const PAGE_SIZE=24; let cursor=null,nextCursor=null,loading=false; const $=id=>document.getElementById(id); let previousCursors=[];
async function guard(){const {admin}=await requireAuthenticatedAdmin();if(!admin||!hasRole(admin.role,ROLES.REVIEWER))throw new Error("INSUFFICIENT_PERMISSIONS");return admin}
function filters(){return {branchId:$("resource-branch").value||null,subjectId:$("resource-subject").value||null,categoryId:$("resource-category").value||null,type:$("resource-type").value||null,active:$("resource-active").value===""?null:$("resource-active").value==="true",search:$("resource-search").value.trim()||null}}
function option(s,v,l){const o=document.createElement("option");o.value=v;o.textContent=l;s.append(o)}
async function loadFilters(){const [b,s,c]=await Promise.all([getAllSmall("branches"),getAllSmall("subjects"),getAllSmall("categories")]);b.forEach(x=>{option($("resource-branch"),x.id,x.name);option($("form-branches"),x.id,x.name)});s.forEach(x=>{option($("resource-subject"),x.id,x.name);option($("form-subject"),x.id,x.name)});c.forEach(x=>{option($("resource-category"),x.id,x.name);option($("form-category"),x.id,x.name)})}
function showModal(item=null){$("resource-modal").hidden=false;$("resource-modal-title").textContent=item?"تعديل مصدر":"إضافة مصدر";$("resource-id").value=item?.id||"";$("form-title").value=item?.title||"";$("form-url").value=item?.url||"";$("form-type").value=item?.type||"";$("form-order").value=item?.order??0;$("form-subject").value=item?.subjectId||"";$("form-category").value=item?.categoryId||"";$("form-description").value=item?.description||"";$("form-keywords").value=(item?.keywords||[]).join(", ");$("form-tags").value=(item?.tags||[]).join(", ");$("form-active").checked=item?.active!==false;[...$("form-branches").options].forEach(o=>o.selected=(item?.branchIds||[]).includes(o.value));$("form-error").hidden=true;$("form-title").focus()}
function closeModal(){$("resource-modal").hidden=true}
function msg(e){return ({RESOURCE_TITLE_REQUIRED:"العنوان مطلوب",RESOURCE_URL_REQUIRED:"الرابط مطلوب",RESOURCE_URL_INVALID:"الرابط غير صالح",RESOURCE_URL_PROTOCOL:"الرابط يجب أن يستخدم http أو https",RESOURCE_URL_DUPLICATE:"الرابط موجود مسبقًا",RESOURCE_BRANCH_REQUIRED:"اختر فرعًا واحدًا على الأقل",RESOURCE_SUBJECT_REQUIRED:"اختر المادة",RESOURCE_ORDER_INVALID:"الترتيب غير صالح",UNAUTHORIZED_ADMIN:"ليس لديك صلاحية",INSUFFICIENT_PERMISSIONS:"ليس لديك صلاحية"})[e.message]||"تعذر تنفيذ العملية."}
function render(items){const root=$("resource-list");root.replaceChildren();if(!items.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="لا توجد مصادر مطابقة.";root.append(empty);return}for(const item of items){const a=document.createElement("article");a.className="card resource-card";const t=document.createElement("h3");t.textContent=item.title||"مصدر بدون عنوان";const m=document.createElement("p");m.textContent=[item.type,item.active===false?"معطّل":"مفعّل"].filter(Boolean).join(" • ");const body=document.createElement("div");body.append(t,m);const actions=document.createElement("div");actions.className="actions";const edit=document.createElement("button");edit.className="button";edit.type="button";edit.textContent="تعديل";edit.addEventListener("click",()=>showModal(item));const toggle=document.createElement("button");toggle.className="button";toggle.type="button";toggle.textContent=item.active===false?"تفعيل":"تعطيل";toggle.addEventListener("click",async()=>{if(!confirm(item.active===false?"تفعيل المصدر؟":"تعطيل المصدر؟"))return;try{await resourceRepository.setResourceActive(item.id,item.active===false);await load(true)}catch(e){console.error(e);alert(msg(e))}});const del=document.createElement("button");del.className="button danger";del.type="button";del.textContent="حذف";del.addEventListener("click",async()=>{if(!confirm("حذف المصدر نهائيًا؟"))return;try{await resourceRepository.removeResource(item.id);await load(true)}catch(e){console.error(e);alert(msg(e))}});actions.append(edit,toggle,del);a.append(body,actions);root.append(a)}}
async function load(reset=false){if(loading)return;loading=true;if(reset){cursor=null;nextCursor=null;previousCursors=[]}const list=$("resource-list");list.replaceChildren();const loadingState=document.createElement("div");loadingState.className="empty";loadingState.setAttribute("role","status");loadingState.textContent="جاري التحميل...";list.append(loadingState);try{const r=await resourceRepository.getResources({...filters(),limit:PAGE_SIZE,cursor});nextCursor=r.nextCursor;render(r.items);const p=$("resource-pagination");p.replaceChildren();const prev=document.createElement("button");prev.className="button";prev.type="button";prev.textContent="السابق";prev.disabled=!previousCursors.length;prev.addEventListener("click",async()=>{cursor=previousCursors.pop()||null;await load(false)});const next=document.createElement("button");next.className="button";next.type="button";next.textContent="التالي";next.disabled=!nextCursor;next.addEventListener("click",async()=>{if(cursor)previousCursors.push(cursor);cursor=nextCursor;await load(false)});p.append(prev,next)}catch(e){console.error("Admin resources load failed",e);list.replaceChildren();const error=document.createElement("div");error.className="error-box";error.setAttribute("role","alert");error.textContent="تعذر تحميل المصادر.";list.append(error)}finally{loading=false}}
$("add-resource").addEventListener("click",()=>showModal());document.querySelectorAll("[data-close-resource]").forEach(x=>x.addEventListener("click",closeModal));$("resource-form").addEventListener("submit",async e=>{e.preventDefault();const error=$("form-error"),button=$("save-resource");error.hidden=true;button.disabled=true;try{await resourceRepository.saveResource($("resource-id").value||null,{title:$("form-title").value,url:$("form-url").value,type:$("form-type").value,order:$("form-order").value,subjectId:$("form-subject").value,categoryId:$("form-category").value,branchIds:[...$("form-branches").selectedOptions].map(o=>o.value),keywords:$("form-keywords").value.split(","),tags:$("form-tags").value.split(","),description:$("form-description").value,active:$("form-active").checked});closeModal();await load(true)}catch(e){console.error("Resource save failed",e);error.textContent=msg(e);error.hidden=false}finally{button.disabled=false}});
await guard();renderNavbar();renderFooter();await loadFilters();await load(true);let timer;$("resource-search").addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>load(true),350)});for(const id of ["resource-branch","resource-subject","resource-category","resource-type","resource-active"])$(id).addEventListener("change",()=>load(true));
