import { requireAdmin, ROLES } from '../services/firebase/adminCore.js';
import { getSolutions, createSolution, updateSolution, deleteSolution } from '../repositories/solutionRepository.js';
import { renderNavbar, renderFooter } from '../components/layout.js';
await requireAdmin(ROLES.CONTENT_ADMIN); renderNavbar(); renderFooter();
const $=id=>document.getElementById(id); let cursor=null,editingId=null,loading=false;
const safeUrl=v=>{if(!v)return true;try{return ['http:','https:'].includes(new URL(v).protocol)}catch{return false}};
function render(items){const root=$('solution-list');root.replaceChildren();if(!items.length){root.innerHTML='<div class="empty">لا توجد حلول.</div>';return}items.forEach(x=>{const card=document.createElement('article');card.className='card admin-row';const info=document.createElement('div');const h=document.createElement('h3');h.textContent=x.title||'بدون عنوان';const p=document.createElement('p');p.textContent=[x.category,x.active===false?'معطّل':'مفعّل'].filter(Boolean).join(' • ');info.append(h,p);const a=document.createElement('div');a.className='actions';const e=document.createElement('button');e.className='button';e.textContent='تعديل';e.onclick=()=>open(x);const d=document.createElement('button');d.className='button danger';d.textContent='حذف';d.onclick=()=>remove(x);a.append(e,d);card.append(info,a);root.append(card)})}
function open(x=null){editingId=x?.id||null;$('form-title').textContent=editingId?'تعديل الحل':'إضافة حل';$('title').value=x?.title||'';$('description').value=x?.description||'';$('url').value=x?.url||'';$('category').value=x?.category||'';$('order').value=Number(x?.order)||0;$('active').checked=x?.active!==false;$('solution-dialog').showModal();$('title').focus()}
function close(){if($('solution-dialog').open)$('solution-dialog').close();editingId=null}
async function load(){if(loading)return;loading=true;try{const r=await getSolutions({pageSize:24,cursor});render(r.items);const p=$('pagination');p.replaceChildren();if(cursor){const back=document.createElement('button');back.className='button';back.textContent='لا توجد صفحة سابقة في هذا العرض';back.disabled=true;p.append(back)}const next=document.createElement('button');next.className='button';next.textContent='التالي';next.disabled=!r.nextCursor;next.onclick=async()=>{cursor=r.nextCursor;await load()};p.append(next)}catch(e){console.error(e);$('solution-list').innerHTML='<div class="error-box">تعذر تحميل الحلول.</div>'}finally{loading=false}}
async function remove(x){if(!confirm(`تأكيد حذف «${x.title||''}»؟`))return;try{await deleteSolution(x.id);cursor=null;await load()}catch(e){console.error(e);alert('تعذر الحذف.')}}
$('add-solution').onclick=()=>open();$('cancel').onclick=close;$('solution-form').addEventListener('submit',async e=>{e.preventDefault();const title=$('title').value.trim(),url=$('url').value.trim(),order=Number($('order').value);if(!title)return alert('العنوان مطلوب.');if(!Number.isInteger(order)||order<0)return alert('الترتيب غير صحيح.');if(!safeUrl(url))return alert('الرابط يجب أن يكون http أو https.');const data={title,description:$('description').value.trim(),url,category:$('category').value.trim(),order,active:$('active').checked,updatedAt:new Date()};try{if(editingId)await updateSolution(editingId,data);else await createSolution({...data,createdAt:new Date()});close();cursor=null;await load()}catch(err){console.error(err);alert('تعذر حفظ الحل.')}});await load();