import { requireAdmin, ROLES } from '../services/firebase/adminCore.js';
import { db } from '../services/firebase.js';
import { collection, getDocs, limit, query, serverTimestamp, where, writeBatch, doc } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { normalizeUrl } from '../repositories/resourceRepository.js';
import { validateTest } from '../repositories/testRepository.js';
await requireAdmin(ROLES.CONTENT_ADMIN);
const $=id=>document.getElementById(id),kind=$('kind'),json=$('json'),status=$('status');
const templates={
resource:{templateType:'minhaj-resource-v1',items:[{title:'عنوان المصدر',url:'https://example.com/file',description:'وصف مختصر',type:'book',subjectId:'SUBJECT_ID',categoryId:'CATEGORY_ID',branchIds:['BRANCH_ID'],keywords:['رياضيات'],tags:['مهم'],author:'',order:0,active:true}]},
foundation:{templateType:'minhaj-foundation-v1',items:[{title:'عنوان التأسيس',url:'https://example.com/file',description:'وصف',type:'lesson',level:'beginner',subjectId:'SUBJECT_ID',branchIds:['BRANCH_ID'],keywords:['أساسيات'],author:'',order:0,active:true}]},
solution:{templateType:'minhaj-solution-v1',items:[{title:'عنوان الحل',problem:'السؤال',solution:'الحل',steps:['الخطوة الأولى','الخطوة الثانية'],notes:'',url:'',category:'رياضيات',subjectId:'SUBJECT_ID',branchIds:['BRANCH_ID'],keywords:['تفاضل'],order:0,active:true}]},
flashcard:{templateType:'minhaj-flashcard-v1',items:[{question:'السؤال',answer:'الإجابة',explanation:'شرح مختصر',subjectId:'SUBJECT_ID',branchId:'BRANCH_ID',difficulty:'medium',tags:['مراجعة'],order:0,active:true}]},
test:{templateType:'minhaj-test-v1',items:[{title:'اسم الاختبار',description:'وصف الاختبار',subjectId:'SUBJECT_ID',branchIds:['BRANCH_ID'],durationMinutes:20,order:0,active:true,questions:[{id:'q1',question:'السؤال الأول',type:'mcq',options:['الخيار 1','الخيار 2','الخيار 3','الخيار 4'],answer:'الخيار 1',explanation:'',points:1},{id:'q2',question:'هل العبارة صحيحة؟',type:'true_false',options:['صح','خطأ'],answer:'صح',explanation:'',points:1}]}]}
};
function showTemplate(){json.value=JSON.stringify(templates[kind.value],null,2);status.textContent='القالب جاهز للنسخ.'}
function parse(){let data;try{data=JSON.parse(json.value)}catch{throw Error('JSON غير صالح.')}if(!data||!Array.isArray(data.items)||!data.items.length)throw Error('يجب أن يحتوي JSON على items.');return data.items}
async function resourceExists(url){const n=normalizeUrl(url);if(!n)return false;const snap=await getDocs(query(collection(db,'resources'),where('url','==',n),limit(1)));return !snap.empty}
async function importItems(){const items=parse(),target={resource:'resources',foundation:'foundations',solution:'solutions',flashcard:'flashcards',test:'tests'}[kind.value],clean=[],skipped=[];for(const item of items){if(target==='resources'){if(!item.title||!item.url)throw Error('كل مصدر يحتاج title و url.');if(await resourceExists(item.url)){skipped.push(item.title||item.url);continue}clean.push({...item,url:normalizeUrl(item.url),active:item.active!==false,order:Number(item.order)||0})}else if(target==='tests'){clean.push(validateTest(item))}else clean.push({...item,active:item.active!==false,order:Number(item.order)||0})}if(!clean.length)return `لم تتم إضافة عناصر. تم تخطي ${skipped.length} مكرر.`;const batch=writeBatch(db);clean.forEach(item=>batch.set(doc(collection(db,target)),{...item,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await batch.commit();return `تم استيراد ${clean.length} عنصر${skipped.length?`، وتخطي ${skipped.length} رابط مكرر`:''}.`}
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(json.value)}catch{json.select();document.execCommand('copy')}status.textContent='تم نسخ القالب.'};$('loadExample').onclick=showTemplate;kind.onchange=showTemplate;document.getElementById('importButton').onclick=async()=>{const b=document.getElementById('importButton');b.disabled=true;status.textContent='جاري الفحص والاستيراد...';try{status.textContent=await importItems()}catch(e){console.error(e);status.textContent=e.message||'تعذر الاستيراد.'}finally{b.disabled=false}};showTemplate();
