import type { Permission } from '../../app/permissions';
export interface AdminFieldDefinition { key:string; label:string; type:'text'|'textarea'|'url'|'number'|'checkbox'|'select'; required?:boolean; placeholder?:string; relation?:'branches'|'subjects'|'categories'; }
export interface AdminEntityDefinition { id:string; collection:string; label:string; permission:Permission; fields:readonly AdminFieldDefinition[]; }
export const ADMIN_ENTITIES: readonly AdminEntityDefinition[] = [
{id:'branches',collection:'branches',label:'الفروع',permission:'manageBranches',fields:[{key:'name',label:'الاسم',type:'text',required:true},{key:'description',label:'الوصف',type:'textarea'},{key:'icon',label:'الأيقونة',type:'text'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]},
{id:'subjects',collection:'subjects',label:'المواد',permission:'manageSubjects',fields:[{key:'name',label:'اسم المادة',type:'text',required:true},{key:'description',label:'الوصف',type:'textarea'},{key:'icon',label:'الأيقونة',type:'text'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]},
{id:'categories',collection:'categories',label:'التصنيفات',permission:'manageCategories',fields:[{key:'name',label:'اسم التصنيف',type:'text',required:true},{key:'description',label:'الوصف',type:'textarea'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]},
{id:'resources',collection:'resources',label:'المصادر',permission:'manageResources',fields:[{key:'title',label:'العنوان',type:'text',required:true},{key:'description',label:'الوصف',type:'textarea'},{key:'url',label:'الرابط',type:'url',required:true},{key:'type',label:'النوع',type:'text',required:true},{key:'branchId',label:'الفرع',type:'select',relation:'branches'},{key:'subjectId',label:'المادة',type:'select',relation:'subjects'},{key:'categoryId',label:'التصنيف',type:'select',relation:'categories'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]},
{id:'foundations',collection:'foundations',label:'التأسيس',permission:'manageFoundations',fields:[{key:'title',label:'العنوان',type:'text',required:true},{key:'description',label:'الوصف',type:'textarea'},{key:'url',label:'الرابط',type:'url'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]},
{id:'solutions',collection:'solutions',label:'الحلول',permission:'manageSolutions',fields:[{key:'title',label:'العنوان',type:'text',required:true},{key:'category',label:'التصنيف',type:'text'},{key:'content',label:'المحتوى',type:'textarea',required:true},{key:'links',label:'الروابط',type:'textarea'},{key:'order',label:'الترتيب',type:'number'},{key:'active',label:'نشط',type:'checkbox'}]}
] as const;
