import { useEffect, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { branches, resources, subjects, foundations, solutions } from '../repositories';
import { Empty, Loading } from '../components/Layout';
import type { BaseDocument, Branch, Resource, Subject, Foundation, Solution, ListOptions, Page } from '../types';
import { normalizeSearchText } from '../utils/validation';
type Repo<T extends BaseDocument>={list:(o?:ListOptions)=>Promise<Page<T>>};
function CollectionPage<T extends BaseDocument>({title,repo,render}:{title:string;repo:Repo<T>;render:(item:T)=>ReactNode}){const[items,setItems]=useState<T[]>([]),[loading,setLoading]=useState(true),[cursor,setCursor]=useState<string>(),[more,setMore]=useState(false),[search,setSearch]=useState('');async function load(reset=false){setLoading(true);try{const p=await repo.list({pageSize:20,cursor:reset?undefined:cursor});setItems(reset?p.items:[...items,...p.items]);setCursor(p.nextCursor);setMore(p.hasMore)}finally{setLoading(false)}}useEffect(()=>{void load(true)},[]);const visible=search?items.filter(x=>normalizeSearchText(JSON.stringify(x)).includes(normalizeSearchText(search))):items;return <section><div className="page-head"><h1>{title}</h1><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث..." aria-label="بحث"/></div><div className="grid">{visible.map(x=><article className="card" key={x.id}>{render(x)}</article>)}</div>{!loading&&!visible.length&&<Empty/>}{loading&&<Loading/>}{more&&!loading&&<button className="button" onClick={()=>void load()}>تحميل المزيد</button>}</section>}
export function Home(){return <section className="hero"><span className="eyebrow">MINHAJ</span><h1>مِنهَاج</h1><p>منصة تعليمية تجمع المصادر، المواد، التأسيس والأدوات في مكان واحد.</p><div className="actions"><Link className="button" to="/resources">استكشف المصادر</Link><Link className="button secondary" to="/ai">اسأل مساعد منهاج</Link></div></section>}
export function Branches(){return <CollectionPage title="الفروع" repo={branches} render={x=><><h2>{(x as Branch).icon} {(x as Branch).name}</h2><p>{(x as Branch).description}</p></>}/>}
export function Subjects(){return <CollectionPage title="المواد" repo={subjects} render={x=><><h2>{(x as Subject).icon} {(x as Subject).name}</h2><p>{(x as Subject).description}</p></>}/>}
export function Resources(){return <CollectionPage title="المصادر" repo={resources} render={x=><><h2>{(x as Resource).title}</h2><p>{(x as Resource).description}</p><a href={(x as Resource).url} target="_blank" rel="noopener noreferrer">فتح المصدر ↗</a></>}/>}
export function Foundation(){return <CollectionPage title="التأسيس" repo={foundations} render={x=><><h2>{(x as Foundation).title}</h2><p>{(x as Foundation).description}</p>{(x as Foundation).url&&<a href={(x as Foundation).url} target="_blank" rel="noopener noreferrer">فتح ↗</a>}</>}/>}
export function Solutions(){return <CollectionPage title="حلول ومشاكل" repo={solutions} render={x=><><h2>{(x as Solution).title}</h2><p>{(x as Solution).content}</p></>}/>}
