import { mountShell } from '../components/layout.js';
import { auth } from '../services/firebase.js';
import { getStudentProfile, initStudentAuth, loginStudent, logoutStudent, registerStudent, saveStudentProfile, watchAuth, authErrorMessage } from '../services/studentAuth.js';
import { escapeHtml } from '../core/utils.js';

mountShell('حساب الطالب', `<style>.account-wrap{max-width:760px;margin:0 auto;display:grid;gap:18px}.account-card{padding:26px;border:1px solid var(--color-border);border-radius:24px;background:var(--color-surface);box-shadow:var(--shadow-md)}.account-form{display:grid;gap:14px}.account-form label{display:grid;gap:7px;font-weight:600}.account-form input{width:100%;box-sizing:border-box}.account-tabs{display:flex;gap:8px;margin-bottom:18px}.account-tabs button{border:1px solid var(--color-border);background:var(--color-surface-solid);border-radius:12px;padding:10px 16px;cursor:pointer}.account-tabs button.active{background:var(--color-primary);color:#fff;border-color:var(--color-primary)}.account-message{margin-top:12px}.account-badges{display:flex;flex-wrap:wrap;gap:8px}.account-badge{padding:7px 11px;border-radius:999px;background:var(--color-surface-solid);font-size:13px}.optional,.muted{color:var(--color-muted);font-size:13px}.privacy-note{font-size:13px;padding:13px;border-radius:14px;background:var(--color-surface-solid)}</style><section class="page-head"><span class="eyebrow">اختياري</span><h1>حساب الطالب</h1><p>استخدم منهاج كزائر أو سجّل الدخول لفتح الميزات الشخصية.</p></section><div id="accountRoot" class="account-wrap"></div>`);
const root=document.getElementById('accountRoot');
function guestView(mode='login',message=''){const login=mode==='login';root.innerHTML=`<section class="account-card"><div class="account-tabs"><button type="button" data-mode="login" class="${login?'active':''}">تسجيل الدخول</button><button type="button" data-mode="register" class="${!login?'active':''}">إنشاء حساب</button></div>${login?`<form id="loginForm" class="account-form"><label>البريد الإلكتروني<input id="loginEmail" type="email" autocomplete="email" required></label><label>كلمة المرور<input id="loginPassword" type="password" autocomplete="current-password" required minlength="6"></label><button class="button primary" type="submit">دخول</button></form>`:`<form id="registerForm" class="account-form"><label>الاسم<input id="registerName" maxlength="100" autocomplete="name" required></label><label>البريد الإلكتروني<input id="registerEmail" type="email" maxlength="200" autocomplete="email" required></label><label>كلمة المرور<input id="registerPassword" type="password" minlength="6" autocomplete="new-password" required></label><label>رقم الهوية <span class="optional">(اختياري)</span><input id="registerIdentity" inputmode="numeric" maxlength="32" autocomplete="off"></label><div class="privacy-note">رقم الهوية اختياري ويُحفظ داخل حسابك فقط.</div><button class="button primary" type="submit">إنشاء الحساب</button></form>`}<p id="accountMsg" class="message account-message">${escapeHtml(message)}</p></section><section class="account-card"><h2>ماذا يفتح الحساب؟</h2><div class="account-badges"><span class="account-badge">بطاقاتي</span><span class="account-badge">حفظ التقدم</span><span class="account-badge">المفضلة</span><span class="account-badge">إحصائيات الدراسة</span></div></section>`;root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>guestView(b.dataset.mode));root.querySelector('#loginForm')?.addEventListener('submit',handleLogin);root.querySelector('#registerForm')?.addEventListener('submit',handleRegister)}
async function handleLogin(e){e.preventDefault();const b=e.submitter,msg=root.querySelector('#accountMsg');b.disabled=true;try{await loginStudent(root.querySelector('#loginEmail').value,root.querySelector('#loginPassword').value);await renderUser()}catch(err){msg.textContent=authErrorMessage(err);msg.classList.add('error')}finally{b.disabled=false}}
async function handleRegister(e){e.preventDefault();const b=e.submitter,msg=root.querySelector('#accountMsg');b.disabled=true;try{await registerStudent({name:root.querySelector('#registerName').value,email:root.querySelector('#registerEmail').value,password:root.querySelector('#registerPassword').value,identityNumber:root.querySelector('#registerIdentity').value});await renderUser()}catch(err){msg.textContent=authErrorMessage(err);msg.classList.add('error')}finally{b.disabled=false}}
async function renderUser(){const user=auth.currentUser;if(!user){guestView();return}const profile=await getStudentProfile(user.uid);root.innerHTML=`<section class="account-card"><span class="eyebrow">مسجل دخول</span><h2>أهلًا ${escapeHtml(profile?.name||user.displayName||'طالب')}</h2><p class="muted">${escapeHtml(user.email||'')}</p><div class="actions"><a class="button primary" href="my-flashcards.html">🗂️ بطاقاتي</a><button id="logout" class="button" type="button">تسجيل الخروج</button></div><form id="profileForm" class="account-form" style="margin-top:20px"><label>الاسم<input id="profileName" maxlength="100" required value="${escapeHtml(profile?.name||user.displayName||'')}"></label><label>رقم الهوية <span class="optional">(اختياري)</span><input id="profileIdentity" inputmode="numeric" maxlength="32" value="${escapeHtml(profile?.identityNumber||'')}"></label><button class="button primary" type="submit">حفظ البيانات</button><p id="profileMsg" class="message" role="status"></p></form></section>`;root.querySelector('#profileForm').onsubmit=handleProfileSave;root.querySelector('#logout').onclick=async()=>{await logoutStudent();guestView()}}
async function handleProfileSave(e){e.preventDefault();const b=e.submitter,msg=root.querySelector('#profileMsg');b.disabled=true;try{await saveStudentProfile({name:root.querySelector('#profileName').value,identityNumber:root.querySelector('#profileIdentity').value});msg.textContent='تم حفظ بيانات الحساب.'}catch(err){msg.textContent=authErrorMessage(err);msg.classList.add('error')}finally{b.disabled=false}}
await initStudentAuth();watchAuth(user=>user?renderUser():guestView());if(auth.currentUser)await renderUser();else guestView();
