import { mountShell } from '../components/layout.js';
import { auth } from '../services/firebase.js';
import { getStudentProfile,initStudentAuth,loginStudent,logoutStudent,registerStudent,saveStudentProfile,watchAuth,authErrorMessage } from '../services/studentAuth.js';
import { getMyProblemReports } from '../repositories/problemReportRepository.js';
import { getMySuggestions } from '../repositories/suggestionRepository.js';
import { getAdminApplicationQuestions,getMyAdminApplication,submitAdminApplication } from '../repositories/adminApplicationRepository.js';
import { escapeHtml,setMessage,setBusy } from '../core/utils.js';

mountShell('حساب الطالب',`<section class="page-head"><span class="eyebrow">حسابك في مِنهَاج</span><h1>حساب الطالب</h1><p>إدارة بياناتك ومتابعة البلاغات والاقتراحات وطلبات الانضمام للفريق.</p></section><div id="accountRoot"></div>`);
const root=document.getElementById('accountRoot');
function guestView(mode='login'){const login=mode==='login';root.innerHTML=`<section class="card"><div class="account-tabs"><button type="button" data-mode="login" class="${login?'active':''}">تسجيل الدخول</button><button type="button" data-mode="register" class="${!login?'active':''}">إنشاء حساب</button></div>${login?`<form id="loginForm" class="form-card"><label>البريد الإلكتروني<input id="loginEmail" type="email" required></label><label>كلمة المرور<input id="loginPassword" type="password" minlength="6" required></label><button class="button primary">دخول</button></form>`:`<form id="registerForm" class="form-card"><label>الاسم<input id="registerName" maxlength="100" required></label><label>البريد الإلكتروني<input id="registerEmail" type="email" required></label><label>كلمة المرور<input id="registerPassword" type="password" minlength="6" required></label><label>رقم الهوية<input id="registerIdentity" inputmode="numeric" maxlength="32" placeholder="مطلوب للتقديم لفريق مِنهَاج"></label><button class="button primary">إنشاء الحساب</button></form>`}<p id="accountMsg" class="message"></p></section>`;root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>guestView(b.dataset.mode));root.querySelector('#loginForm')?.addEventListener('submit',handleLogin);root.querySelector('#registerForm')?.addEventListener('submit',handleRegister)}
async function handleLogin(e){e.preventDefault();try{await loginStudent(root.querySelector('#loginEmail').value,root.querySelector('#loginPassword').value);await renderUser()}catch(err){root.querySelector('#accountMsg').textContent=authErrorMessage(err)}}
async function handleRegister(e){e.preventDefault();try{await registerStudent({name:root.querySelector('#registerName').value,email:root.querySelector('#registerEmail').value,password:root.querySelector('#registerPassword').value,identityNumber:root.querySelector('#registerIdentity').value});await renderUser()}catch(err){root.querySelector('#accountMsg').textContent=authErrorMessage(err)}}
function statusLabel(status){return ({open:'مفتوح',resolved:'تم الحل',dismissed:'مغلق',pending:'معلّق',approved:'مقبول',rejected:'مرفوض',archived:'مؤرشف'})[status]||status||'غير معروف'}
async function renderUser(){const user=auth.currentUser;if(!user)return guestView();const profile=await getStudentProfile(user.uid);const [reports,suggestions,application]=await Promise.all([getMyProblemReports(),getMySuggestions(),getMyAdminApplication()]);root.innerHTML=`<section class="card"><span class="eyebrow">مسجل دخول</span><h2>أهلًا ${escapeHtml(profile?.name||user.displayName||'طالب')}</h2><p>${escapeHtml(user.email||'')}</p><form id="profileForm" class="form-card"><label>الاسم<input id="profileName" value="${escapeHtml(profile?.name||user.displayName||'')}" maxlength="100" required></label><label>رقم الهوية<input id="profileIdentity" value="${escapeHtml(profile?.identityNumber||'')}" inputmode="numeric" maxlength="32" placeholder="مطلوب للتقديم لفريق مِنهَاج"></label><button class="button" type="submit">حفظ البيانات</button><p id="profileMsg" class="message"></p></form><div class="actions"><a class="button primary" href="my-flashcards.html">🗂️ بطاقاتي</a><button id="logout" class="button">تسجيل الخروج</button></div></section><section class="card"><h2>بلاغاتي</h2><div class="stack">${reports.length?reports.map(r=>`<article class="admin-row"><strong>${escapeHtml(r.sourceTitle||r.sourceId||'بلاغ')}</strong><span>الحالة: ${escapeHtml(statusLabel(r.status))}</span><p>${escapeHtml(r.description||'')}</p></article>`).join(''):'<p class="message">لا توجد بلاغات مرتبطة بحسابك.</p>'}</div></section><section class="card"><h2>اقتراحاتي</h2><div class="stack">${suggestions.length?suggestions.map(s=>`<article class="admin-row"><strong>${escapeHtml(s.title||'اقتراح')}</strong><span>الحالة: ${escapeHtml(statusLabel(s.status))}</span><p>${escapeHtml(s.description||'')}</p></article>`).join(''):'<p class="message">لا توجد اقتراحات مرتبطة بحسابك.</p>'}</div></section><section class="card team-application"><div class="team-application__intro"><span class="team-application__icon" aria-hidden="true">👥</span><div><span class="eyebrow">فريق مِنهَاج</span><h2>الانضمام إلى فريق مِنهَاج</h2><p>ساهم في تطوير المنصة ومساعدة الطلاب. تتم مراجعة كل طلب قبل منح أي صلاحية.</p></div></div><div class="team-application__notice"><span aria-hidden="true">🔐</span><div><strong>ملاحظة مهمة</strong><p>يجب أن يكون رقم الهوية محفوظًا في حسابك. عند الموافقة ستستخدم نفس حساب Minhaj للدخول إلى لوحة الإدارة، بدون إنشاء حساب جديد.</p></div></div><div id="applicationArea"></div></section>`;
root.querySelector('#logout').onclick=async()=>{await logoutStudent();guestView()};
root.querySelector('#profileForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);try{await saveStudentProfile({name:root.querySelector('#profileName').value,identityNumber:root.querySelector('#profileIdentity').value});setMessage(root.querySelector('#profileMsg'),'تم حفظ البيانات.');await renderUser()}catch(err){setMessage(root.querySelector('#profileMsg'),authErrorMessage(err),true)}finally{setBusy(btn,false)}});
renderApplication(application);
}
function renderApplication(application){const area=root.querySelector('#applicationArea');if(!area)return;if(!application){const identity=root.querySelector('#profileIdentity')?.value.trim();if(!identity){area.innerHTML='<div class="team-application__locked"><span aria-hidden="true">🪪</span><div><strong>رقم الهوية مطلوب</strong><p>أضف رقم هويتك إلى بيانات حسابك أولًا حتى تتمكن من تقديم طلب الانضمام.</p></div><a class="button" href="#profileIdentity" onclick="document.getElementById(\'profileIdentity\')?.focus()">إضافة رقم الهوية</a></div>';return}const questions=getAdminApplicationQuestions();area.innerHTML=`<div class="team-application__form-head"><div><strong>استبيان الانضمام</strong><p>أجب عن الأسئلة بوضوح. الطلب سيصل إلى فريق الإدارة للمراجعة.</p></div><span class="team-application__count">${questions.length} أسئلة</span></div><form id="adminApplicationForm" class="team-application__form">${questions.map((q,i)=>`<label class="team-question"><span class="team-question__number">${i+1}</span><span class="team-question__body"><strong>${escapeHtml(q.label)}</strong><textarea name="${q.id}" maxlength="2000" required rows="4" placeholder="اكتب إجابتك هنا..."></textarea></span></label>`).join('')}<div class="team-application__submit"><button class="button primary" type="submit">إرسال طلب الانضمام</button><p id="applicationMsg" class="message"></p></div></form>`;area.querySelector('form').addEventListener('submit',submitApplication);return}if(application.status==='pending'){area.innerHTML='<div class="team-application__status is-pending"><span class="team-application__status-icon" aria-hidden="true">⏳</span><div><strong>طلبك قيد المراجعة</strong><p>تم استلام طلبك. ستتم مراجعته من فريق الإدارة قبل منح أي صلاحية.</p></div><span class="badge">قيد المراجعة</span></div>';return}if(application.status==='approved'){area.innerHTML='<div class="team-application__status is-approved"><span class="team-application__status-icon" aria-hidden="true">✓</span><div><strong>تم قبول طلبك</strong><p>تم تفعيل صلاحية الإدارة على حساب Minhaj الخاص بك.</p></div><span class="badge">مقبول</span></div>';return}area.innerHTML=`<div class="team-application__status is-rejected"><span class="team-application__status-icon" aria-hidden="true">!</span><div><strong>الطلب السابق: ${escapeHtml(statusLabel(application.status))}</strong><p>${application.reviewerNote?`ملاحظة الإدارة: ${escapeHtml(application.reviewerNote)}`:'يمكنك إعادة التقديم بعد مراجعة الطلب السابق.'}</p></div></div><button id="reapply" class="button primary team-application__reapply" type="button">إعادة التقديم</button>`;area.querySelector('#reapply').onclick=()=>{root.querySelector('#applicationArea').replaceChildren();renderApplication(null)};}
async function submitApplication(event){event.preventDefault();const form=event.currentTarget;const btn=event.submitter;const answers=Object.fromEntries(new FormData(form).entries());setBusy(btn,true);try{await submitAdminApplication(answers);setMessage(form.querySelector('#applicationMsg'),'تم إرسال طلبك للمراجعة.');setTimeout(renderUser,300)}catch(error){const messages={STUDENT_ID_REQUIRED:'يجب إضافة رقم الهوية إلى الحساب قبل التقديم.',ADMIN_APPLICATION_PENDING:'لديك طلب قيد المراجعة بالفعل.',ADMIN_APPLICATION_APPROVED:'تمت الموافقة على طلبك مسبقًا.',ADMIN_APPLICATION_ANSWERS_REQUIRED:'أجب عن جميع الأسئلة.'};setMessage(form.querySelector('#applicationMsg'),messages[error.message]||'تعذر إرسال الطلب.',true)}finally{setBusy(btn,false)}}
await initStudentAuth();watchAuth(user=>user?renderUser():guestView());if(auth.currentUser)await renderUser();else guestView();
