import { mountShell } from '../components/layout.js';
import { escapeHtml } from '../core/utils.js';

mountShell('البطاقات', `<style>
.flashcard-wrap{display:grid;place-items:center;min-height:390px;padding:18px}.flashcard{width:min(720px,100%);min-height:360px;perspective:1200px;cursor:pointer;outline:none}.flashcard-inner{position:relative;width:100%;min-height:360px;transform-style:preserve-3d;transition:transform .55s cubic-bezier(.2,.7,.2,1)}.flashcard.is-flipped .flashcard-inner{transform:rotateY(180deg)}.flashcard-face{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:38px;border:1px solid rgba(255,255,255,.3);border-radius:28px;background:var(--card-bg);color:#fff;box-shadow:0 18px 45px rgba(0,0,0,.18);backface-visibility:hidden;-webkit-backface-visibility:hidden;overflow:hidden}.flashcard-face::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 15% 10%,rgba(255,255,255,.3),transparent 32%),radial-gradient(circle at 90% 85%,rgba(255,255,255,.18),transparent 30%);pointer-events:none}.flashcard-face>*{position:relative;z-index:1}.flashcard-face.answer{transform:rotateY(180deg);background:var(--card-answer-bg)}.flashcard-face .eyebrow{color:rgba(255,255,255,.82)}.flashcard-face h2{font-size:clamp(24px,4vw,38px);line-height:1.5;margin:18px 0;max-width:620px}.flashcard-face p{font-size:clamp(19px,3vw,28px);line-height:1.7;max-width:620px}.flashcard-hint{color:rgba(255,255,255,.82);font-size:14px}.flashcard-count{position:absolute;top:20px;inset-inline-start:24px;color:rgba(255,255,255,.78);font-size:13px}.flashcard:focus-visible .flashcard-face{box-shadow:0 0 0 4px rgba(124,92,255,.3),0 18px 45px rgba(0,0,0,.18)}
</style><section class="page-head"><span class="eyebrow">مِنهَاج</span><h1>البطاقات التعليمية</h1><p>السؤال ظاهر مباشرة. اضغط على البطاقة لتقلب وتكشف الإجابة.</p></section><section class="card"><div id="status" class="message" role="status"></div><div id="list" class="flashcard-wrap" aria-live="polite"></div><div class="actions"><button id="prev" class="button" type="button">السابق</button><button id="next" class="button primary" type="button">التالي</button></div><button id="more" class="button" type="button" hidden>تحميل بطاقات إضافية</button></section>`);

const list=document.getElementById('list'),status=document.getElementById('status'),more=document.getElementById('more'),prev=document.getElementById('prev'),next=document.getElementById('next');
let rows=[],index=0,cursor=null,loading=false;let repositoriesPromise;const seenIds=new Set();
const palettes=[['linear-gradient(135deg,#4f46e5,#7c3aed)','linear-gradient(135deg,#4338ca,#6d28d9)'],['linear-gradient(135deg,#0284c7,#06b6d4)','linear-gradient(135deg,#0369a1,#0e7490)'],['linear-gradient(135deg,#059669,#14b8a6)','linear-gradient(135deg,#047857,#0f766e)'],['linear-gradient(135deg,#d97706,#f59e0b)','linear-gradient(135deg,#b45309,#d97706)'],['linear-gradient(135deg,#db2777,#f43f5e)','linear-gradient(135deg,#be185d,#e11d48)'],['linear-gradient(135deg,#7c3aed,#c026d3)','linear-gradient(135deg,#6d28d9,#a21caf)'],['linear-gradient(135deg,#2563eb,#4f46e5)','linear-gradient(135deg,#1d4ed8,#4338ca)'],['linear-gradient(135deg,#0f766e,#0891b2)','linear-gradient(135deg,#115e59,#0e7490)']];
function getRepositories(){return repositoriesPromise??=import('../repositories/resourceRepository.js').then(m=>m.repositories)}
function render(){const item=rows[index];if(!item){list.innerHTML='<div class="empty">لا توجد بطاقات متاحة حاليًا.</div>';prev.disabled=true;next.disabled=true;return}prev.disabled=false;next.disabled=false;const [bg,answerBg]=palettes[index%palettes.length];const question=escapeHtml(item.question||'');const answer=escapeHtml(item.answer||'');const explanation=item.explanation?`<small class="flashcard-hint">${escapeHtml(item.explanation)}</small>`:'';list.innerHTML=`<article class="flashcard" tabindex="0" role="button" aria-label="اضغط لقلب البطاقة" style="--card-bg:${bg};--card-answer-bg:${answerBg}"><div class="flashcard-inner"><div class="flashcard-face question"><span class="eyebrow">السؤال</span><span class="flashcard-count">${index+1} / ${rows.length}</span><h2>${question}</h2><span class="flashcard-hint">اضغط لإظهار الإجابة</span></div><div class="flashcard-face answer"><span class="eyebrow">الإجابة</span><span class="flashcard-count">${index+1} / ${rows.length}</span><p>${answer}</p>${explanation}<span class="flashcard-hint">اضغط للعودة للسؤال</span></div></div></article>`;const card=list.querySelector('.flashcard');const flip=()=>card.classList.toggle('is-flipped');card.onclick=flip;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}}}
async function loadMore(){if(loading||(!cursor&&rows.length))return;loading=true;more.disabled=true;status.textContent='جارٍ تحميل بطاقات إضافية...';try{const repositories=await getRepositories();const result=await repositories.flashcards.page({},30,cursor);const fresh=result.rows.filter(x=>!seenIds.has(x.id));fresh.forEach(x=>seenIds.add(x.id));rows.push(...fresh);cursor=result.nextCursor;more.hidden=!result.hasMore||(fresh.length===0&&!result.nextCursor);status.textContent='';render()}catch(error){console.error('[flashcards.load]',error);status.textContent='تعذر تحميل البطاقات.'}finally{loading=false;more.disabled=false}}
prev.onclick=()=>{if(rows.length){index=index?index-1:rows.length-1;render()}};next.onclick=()=>{if(rows.length){index=index+1<rows.length?index+1:0;render()}};more.onclick=loadMore;loadMore();
