import { mountShell } from '../components/layout.js';
import { initStudentAuth } from '../services/studentAuth.js';
import { getSharedStudentTest, getMyStudentTest } from '../repositories/studentTestRepository.js';
import { escapeHtml } from '../core/utils.js';

mountShell('اختبار مشترك',`<style>.runner{display:grid;gap:16px}.test-hero,.question-card,.result-card{padding:24px;border:1px solid var(--color-border);border-radius:24px;background:var(--color-surface);box-shadow:var(--shadow-sm)}.question-card{display:grid;gap:16px}.answers{display:grid;gap:10px}.answer{display:flex;gap:10px;align-items:flex-start;padding:14px;border:1px solid var(--color-border);border-radius:14px;cursor:pointer}.answer input{margin-top:5px}.top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.timer{font-weight:800}.actions{display:flex;gap:8px;flex-wrap:wrap}.result{font-size:40px;font-weight:900}.review{display:grid;gap:10px}.review-item{padding:14px;border-radius:16px;background:var(--color-surface-solid);border:1px solid var(--color-border)}</style><section id="root" class="runner"><div class="test-hero">جاري تحميل الاختبار...</div></section>`);
const root=document.getElementById('root');const params=new URLSearchParams(location.search);let test=null,index=0,answers=[],started=Date.now(),timer=null;
function same(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>v===b[i])}
function renderStart(){root.innerHTML=`<section class="test-hero"><span class="badge">${test.questions.length} سؤال</span><h1>${escapeHtml(test.title)}</h1><p>${escapeHtml(test.description||'بدون وصف')}</p><p class="muted">${Number(test.durationMinutes||0)?`المدة: ${test.durationMinutes} دقيقة • `:'بدون مؤقت • '}درجة النجاح: ${Number(test.passingScore||0)}%</p><button id="start" class="button primary">ابدأ الاختبار</button></section>`;document.getElementById('start').onclick=start}
function start(){started=Date.now();index=0;answers=[];if(test.randomizeQuestions)test={...test,questions:[...test.questions].sort(()=>Math.random()-.5)};renderQuestion();if(Number(test.durationMinutes)>0){clearInterval(timer);timer=setInterval(()=>{const left=Math.max(0,Number(test.durationMinutes)*60-Math.floor((Date.now()-started)/1000));const el=document.getElementById('timer');if(el)el.textContent=`الوقت المتبقي: ${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0)finish()},1000)}}
function renderQuestion(){const q=test.questions[index];let body='';if(q.type==='ordering'){const current=Array.isArray(answers[index])&&answers[index].length===q.options.length?answers[index]:q.options.slice();answers[index]=current;body=`<div class="answers">${current.map((o,i)=>`<div class="answer"><span>${i+1}.</span><strong>${escapeHtml(o)}</strong><button type="button" class="button" data-up="${i}" ${i===0?'disabled':''}>↑</button><button type="button" class="button" data-down="${i}" ${i===current.length-1?'disabled':''}>↓</button></div>`).join('')}</div>`}else if(q.type==='multi_select'){body=`<div class="answers">${q.options.map(o=>`<label class="answer"><input type="checkbox" value="${escapeHtml(o)}" ${answers[index]?.includes(o)?'checked':''}>${escapeHtml(o)}</label>`).join('')}</div>`}else{body=`<div class="answers">${q.options.map(o=>`<label class="answer"><input type="radio" name="answer" value="${escapeHtml(o)}" ${answers[index]===o?'checked':''}>${escapeHtml(o)}</label>`).join('')}</div>`}root.innerHTML=`<section class="top"><span>السؤال ${index+1} من ${test.questions.length}</span><span id="timer" class="timer"></span></section><section class="question-card"><span class="badge">${q.type==='mcq'?'اختيار واحد':q.type==='true_false'?'صح / خطأ':q.type==='multi_select'?'اختيارات متعددة':'ترتيب'}</span><h2>${escapeHtml(q.question)}</h2>${body}<div class="actions"><button id="prev" class="button" ${index===0?'disabled':''}>السابق</button><button id="next" class="button primary">${index===test.questions.length-1?'إنهاء':'التالي'}</button></div></section>`;root.querySelectorAll('input').forEach(el=>el.onchange=()=>{if(q.type==='multi_select')answers[index]=[...root.querySelectorAll('input:checked')].map(x=>x.value);else answers[index]=el.value});root.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));root.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1));document.getElementById('prev').onclick=()=>{if(index>0){index--;renderQuestion()}};document.getElementById('next').onclick=()=>{if(index===test.questions.length-1)finish();else{index++;renderQuestion()}}}
function move(i,d){const arr=answers[index];[arr[i],arr[i+d]]=[arr[i+d],arr[i]];renderQuestion()}
function finish(){clearInterval(timer);let earned=0,total=0;test.questions.forEach((q,i)=>{const pts=Number(q.points)||1;total+=pts;const a=answers[i];let ok=false;if(q.type==='multi_select')ok=same([...new Set(a||[])].sort(),[...new Set(q.answer||[])].sort());else if(q.type==='ordering')ok=same(a,q.answer);else ok=String(a??'')===String(q.answer??'');if(ok)earned+=pts});const pct=total?Math.round(earned/total*100):0;root.innerHTML=`<section class="result-card"><span class="badge">انتهى الاختبار</span><h1>النتيجة</h1><div class="result">${pct}%</div><p>${earned} من ${total} نقطة • ${pct>=Number(test.passingScore||0)?'ناجح':'يحتاج مراجعة'}</p><div class="actions"><button id="review" class="button primary">مراجعة الإجابات</button><button id="retry" class="button">إعادة الاختبار</button></div></section>`;document.getElementById('review').onclick=renderReview;document.getElementById('retry').onclick=start}
function renderReview(){root.innerHTML=`<section class="review"><div class="top"><h2>مراجعة الإجابات</h2><button id="backResult" class="button">النتيجة</button></div>${test.questions.map((q,i)=>{const a=answers[i];const ok=q.type==='multi_select'?same([...new Set(a||[])].sort(),[...new Set(q.answer||[])].sort()):q.type==='ordering'?same(a,q.answer):String(a??'')===String(q.answer??'');return`<article class="review-item"><b>${i+1}. ${escapeHtml(q.question)}</b><p>إجابتك: ${escapeHtml(Array.isArray(a)?a.join(' ← '):String(a||'لم تُجب'))}</p><p>الإجابة الصحيحة: ${escapeHtml(Array.isArray(q.answer)?q.answer.join(' ← '):String(q.answer))}</p><strong>${ok?'✓ صحيحة':'✗ غير صحيحة'}</strong>${q.explanation?`<p class="muted">${escapeHtml(q.explanation)}</p>`:''}</article>`}).join('')}</section>`;document.getElementById('backResult').onclick=start}
async function load(){try{await initStudentAuth();const share=params.get('share');const privateId=params.get('test');test=share?await getSharedStudentTest(share):privateId?await getMyStudentTest(privateId):null;if(!test)throw Error('NOT_FOUND');renderStart()}catch(e){root.innerHTML='<section class="result-card"><h2>الاختبار غير موجود</h2><p class="muted">قد يكون الرابط غير صحيح أو تم حذف الاختبار.</p></section>'}}
load();
