import { mountShell } from '../components/layout.js';
import { escapeHtml } from '../core/utils.js';
import { getActiveTests, getTest } from '../repositories/testRepository.js';

mountShell('الاختبارات', `<section class="page-head"><span class="eyebrow">مِنهَاج</span><h1>الاختبارات</h1><p>اختبر فهمك واحصل على نتيجتك مباشرة.</p></section><section class="card"><div class="toolbar test-filters"><input id="search" type="search" placeholder="ابحث عن اختبار..." aria-label="البحث في الاختبارات"><select id="subject" aria-label="تصفية حسب المادة"><option value="">كل المواد</option></select><select id="branch" aria-label="تصفية حسب الفرع"><option value="">كل الفروع</option></select></div><div id="list" class="grid" aria-live="polite"><div class="empty">جاري تحميل الاختبارات...</div></div><div id="status" class="message" role="status"></div></section><section id="testView" class="card" hidden></section>`);
const list=document.getElementById('list'),status=document.getElementById('status'),view=document.getElementById('testView'),search=document.getElementById('search'),subject=document.getElementById('subject'),branch=document.getElementById('branch');let tests=[];
const uniqueValues=(key)=>[...new Set(tests.map(t=>String(t?.[key]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));
function fillFilters(){for(const [select,values] of [[subject,uniqueValues('subjectId')],[branch,[...new Set(tests.flatMap(t=>Array.isArray(t.branchIds)?t.branchIds:[]).map(String).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'))]])for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=value;select.append(o)}}
function renderList(){const q=search.value.trim().toLowerCase(),s=subject.value,b=branch.value;const filtered=tests.filter(t=>(!q||`${t.title||''} ${t.description||''}`.toLowerCase().includes(q))&&(!s||String(t.subjectId||'')===s)&&(!b||Array.isArray(t.branchIds)&&t.branchIds.includes(b)));list.replaceChildren();if(!filtered.length){const e=document.createElement('div');e.className='empty';e.textContent='لا توجد اختبارات مطابقة للبحث.';list.append(e);return}filtered.forEach(t=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<span class="eyebrow">اختبار</span><h2>${escapeHtml(t.title||'اختبار')}</h2><p class="muted">${escapeHtml(t.description||'')}</p><p>${(t.questions||[]).length} سؤال${t.durationMinutes?` • ${t.durationMinutes} دقيقة`:''}</p>`;const b=document.createElement('button');b.className='button primary';b.type='button';b.textContent='ابدأ الاختبار';b.onclick=()=>start(t.id);card.append(b);list.append(card)})}
function answerKey(value){const v=String(value??'').trim().toLowerCase();if(v==='صح')return'true';if(v==='خطأ')return'false';return v}
function sameAnswers(a,b){const x=[...(Array.isArray(a)?a:[])].map(String).sort(),y=[...(Array.isArray(b)?b:[])].map(String).sort();return x.length===y.length&&x.every((v,i)=>v===y[i])}
function sameOrder(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>String(v)===String(b[i]))}
async function start(id){const t=await getTest(id);if(!t||!Array.isArray(t.questions)||!t.questions.length){status.textContent='تعذر فتح الاختبار.';return}list.hidden=true;document.querySelector('.test-filters').hidden=true;view.hidden=false;let index=0,score=0,answers=[],remaining=Math.max(0,Number(t.durationMinutes)||0)*60,timer=null;const qs=t.questions;
function finish(timedOut=false){if(timer)clearInterval(timer);const total=qs.reduce((n,q)=>n+(Number(q.points)||1),0),percent=total?Math.round(score/total*100):0;view.innerHTML=`<div class="page-head"><span class="eyebrow">${timedOut?'انتهى الوقت':'انتهى الاختبار'}</span><h2>نتيجتك: ${score} / ${total}</h2><p class="test-score">${percent}%</p><p>${timedOut?'تم إنهاء الاختبار تلقائيًا لانتهاء الوقت.':''}</p></div><div class="test-review">${qs.map((q,i)=>{const a=answers[i],ok=q.type==='ordering'?sameOrder(a,q.answer):q.type==='multi_select'?sameAnswers(a,q.answer):answerKey(a)===answerKey(q.answer);const correct=Array.isArray(q.answer)?q.answer.join(' ← '):q.answer;const given=Array.isArray(a)?a.join(' ← '):(a||'لم تُجب');return `<article class="test-review-item"><strong>${i+1}. ${escapeHtml(q.question)}</strong><p>إجابتك: ${escapeHtml(given)}</p><p>${ok?'إجابة صحيحة':'الإجابة الصحيحة: '+escapeHtml(correct)}</p>${q.explanation?`<p class="muted">${escapeHtml(q.explanation)}</p>`:''}</article>`}).join('')}</div><div class="actions"><button id="retry" class="button primary" type="button">إعادة الاختبار</button><button id="back" class="button" type="button">العودة للاختبارات</button></div>`;document.getElementById('retry').onclick=()=>start(id);document.getElementById('back').onclick=()=>{view.hidden=true;list.hidden=false;document.querySelector('.test-filters').hidden=false;renderList()}}
function renderQ(){const q=qs[index],isOrder=q.type==='ordering',options=q.type==='true_false'?['صح','خطأ']:q.options||[],multi=q.type==='multi_select',current=Array.isArray(answers[index])?answers[index]:[],orderValues=isOrder?(Array.isArray(answers[index])?answers[index]:options):[];const timeText=remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'';view.innerHTML=`<div class="section-head"><div><span class="eyebrow">السؤال ${index+1} من ${qs.length}</span><h2>${escapeHtml(q.question)}</h2>${multi?'<p class="muted">اختر كل الإجابات الصحيحة.</p>':''}${isOrder?'<p class="muted">رتّب العناصر من الأول إلى الأخير.</p>':''}</div><div class="test-meta">${remaining?`<strong id="timer" aria-live="polite">${timeText}</strong>`:''}<button id="exitTest" class="button" type="button">خروج</button></div></div><div class="stack">${isOrder?`<div id="orderOptions" class="stack">${orderValues.map((o,i)=>`<div class="card test-option" data-value="${escapeHtml(String(o))}"><span>${escapeHtml(String(o))}</span><span class="actions"><button class="button order-up" type="button" data-index="${i}" ${i===0?'disabled':''}>↑</button><button class="button order-down" type="button" data-index="${i}" ${i===orderValues.length-1?'disabled':''}>↓</button></span></div>`).join('')}<p class="muted">استخدم ↑ و ↓ لتغيير الترتيب.</p></div>`:options.map(o=>{const value=String(o),checked=multi?current.includes(value):answers[index]===value;return `<label class="card test-option"><input type="${multi?'checkbox':'radio'}" name="answer" value="${escapeHtml(value)}" ${checked?'checked':''}> ${escapeHtml(value)}</label>`}).join('')}<div class="actions"><button id="nextQ" class="button primary" type="button">${index===qs.length-1?'إنهاء الاختبار':'التالي'}</button></div></div>`;
if(isOrder){const container=document.getElementById('orderOptions');container.querySelectorAll('.order-up,.order-down').forEach(btn=>btn.onclick=()=>{const items=[...container.querySelectorAll('.test-option')],i=Number(btn.dataset.index),j=btn.classList.contains('order-up')?i-1:i+1;if(j<0||j>=items.length)return;const values=items.map(x=>x.dataset.value);[values[i],values[j]]=[values[j],values[i]];answers[index]=values;renderQ()})}
document.getElementById('exitTest').onclick=()=>{if(timer)clearInterval(timer);view.hidden=true;list.hidden=false;document.querySelector('.test-filters').hidden=false;renderList()};document.getElementById('nextQ').onclick=()=>{let selected;if(isOrder)selected=[...view.querySelectorAll('#orderOptions .test-option')].map(x=>x.dataset.value);else if(multi)selected=[...view.querySelectorAll('input[name="answer"]:checked')].map(x=>x.value);else selected=view.querySelector('input[name="answer"]:checked')?.value;if(!selected||(Array.isArray(selected)&&!selected.length)){status.textContent='اختر إجابة أولًا.';return}status.textContent='';answers[index]=selected;const correct=isOrder?sameOrder(selected,q.answer):multi?sameAnswers(selected,q.answer):answerKey(selected)===answerKey(q.answer);if(correct)score+=Number(q.points)||1;if(index<qs.length-1){index++;renderQ()}else finish()}}
if(remaining){timer=setInterval(()=>{remaining--;const el=document.getElementById('timer');if(el)el.textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0)finish(true)},1000)}renderQ()}
search.addEventListener('input',renderList);subject.addEventListener('change',renderList);branch.addEventListener('change',renderList);getActiveTests().then(r=>{tests=r;fillFilters();status.textContent='';renderList()}).catch(e=>{console.error(e);status.textContent='تعذر تحميل الاختبارات.'});