import { mountShell } from '../components/layout.js';
import { escapeHtml } from '../core/utils.js';
import { getActiveTests, getTest } from '../repositories/testRepository.js';

mountShell('الاختبارات', `<section class="page-head"><span class="eyebrow">مِنهَاج</span><h1>الاختبارات</h1><p>اختبر فهمك واحصل على نتيجتك مباشرة.</p></section><section class="card"><div class="toolbar test-filters"><input id="search" type="search" placeholder="ابحث عن اختبار..." aria-label="البحث في الاختبارات"><select id="subject" aria-label="تصفية حسب المادة"><option value="">كل المواد</option></select><select id="branch" aria-label="تصفية حسب الفرع"><option value="">كل الفروع</option></select></div><div id="list" class="grid" aria-live="polite"><div class="empty">جاري تحميل الاختبارات...</div></div><div id="status" class="message" role="status"></div></section><section id="testView" class="card" hidden></section>`);
const list=document.getElementById('list'),status=document.getElementById('status'),view=document.getElementById('testView'),search=document.getElementById('search'),subject=document.getElementById('subject'),branch=document.getElementById('branch');let tests=[];
const uniqueValues=(key)=>[...new Set(tests.map(t=>String(t?.[key]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));
function fillFilters(){for(const [select,values] of [[subject,uniqueValues('subjectId')],[branch,[...new Set(tests.flatMap(t=>Array.isArray(t.branchIds)?t.branchIds:[]).map(String).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'))]])for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=value;select.append(o)}}
function renderList(){const q=search.value.trim().toLowerCase(),s=subject.value,b=branch.value;const filtered=tests.filter(t=>(!q||`${t.title||''} ${t.description||''}`.toLowerCase().includes(q))&&(!s||String(t.subjectId||'')===s)&&(!b||Array.isArray(t.branchIds)&&t.branchIds.includes(b)));list.replaceChildren();if(!filtered.length){const e=document.createElement('div');e.className='empty';e.textContent='لا توجد اختبارات مطابقة للبحث.';list.append(e);return}filtered.forEach(t=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<span class="eyebrow">اختبار</span><h2>${escapeHtml(t.title||'اختبار')}</h2><p class="muted">${escapeHtml(t.description||'')}</p><p>${(t.questions||[]).length} سؤال${t.durationMinutes?` • ${t.durationMinutes} دقيقة`:''}</p>`;const b=document.createElement('button');b.className='button primary';b.type='button';b.textContent='ابدأ الاختبار';b.onclick=()=>start(t.id);card.append(b);list.append(card)})}
function answerKey(value){const v=String(value||'').trim().toLowerCase();if(v==='صح')return'true';if(v==='خطأ')return'false';return v}
async function start(id){const t=await getTest(id);if(!t||!Array.isArray(t.questions)||!t.questions.length){status.textContent='تعذر فتح الاختبار.';return}list.hidden=true;document.querySelector('.test-filters').hidden=true;view.hidden=false;let index=0,score=0,answers=[],startedAt=Date.now(),remaining=Math.max(0,Number(t.durationMinutes)||0)*60,timer=null;const qs=t.questions;
function finish(timedOut=false){if(timer)clearInterval(timer);const total=qs.reduce((n,q)=>n+(Number(q.points)||1),0),percent=total?Math.round(score/total*100):0;view.innerHTML=`<div class="page-head"><span class="eyebrow">${timedOut?'انتهى الوقت':'انتهى الاختبار'}</span><h2>نتيجتك: ${score} / ${total}</h2><p class="test-score">${percent}%</p><p>${timedOut?'تم إنهاء الاختبار تلقائيًا لانتهاء الوقت.':''}</p></div><div class="test-review">${qs.map((q,i)=>{const ok=answerKey(answers[i])===answerKey(q.answer);return `<article class="test-review-item"><strong>${i+1}. ${escapeHtml(q.question)}</strong><p>إجابتك: ${escapeHtml(answers[i]||'لم تُجب')}</p><p>${ok?'إجابة صحيحة':'الإجابة الصحيحة: '+escapeHtml(q.answer)}</p>${q.explanation?`<p class="muted">${escapeHtml(q.explanation)}</p>`:''}</article>`}).join('')}</div><div class="actions"><button id="retry" class="button primary" type="button">إعادة الاختبار</button><button id="back" class="button" type="button">العودة للاختبارات</button></div>`;document.getElementById('retry').onclick=()=>start(id);document.getElementById('back').onclick=()=>{view.hidden=true;list.hidden=false;document.querySelector('.test-filters').hidden=false;renderList()}}
function renderQ(){const q=qs[index],options=q.type==='true_false'?['صح','خطأ']:q.options||[];const timeText=remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'';view.innerHTML=`<div class="section-head"><div><span class="eyebrow">السؤال ${index+1} من ${qs.length}</span><h2>${escapeHtml(q.question)}</h2></div><div class="test-meta">${remaining?`<strong id="timer" aria-live="polite">${timeText}</strong>`:''}<button id="exitTest" class="button" type="button">خروج</button></div></div><div class="stack">${options.map(o=>`<label class="card test-option"><input type="radio" name="answer" value="${escapeHtml(String(o))}" ${answers[index]===String(o)?'checked':''}> ${escapeHtml(String(o))}</label>`).join('')}<div class="actions"><button id="nextQ" class="button primary" type="button">${index===qs.length-1?'إنهاء الاختبار':'التالي'}</button></div></div>`;document.getElementById('exitTest').onclick=()=>{if(timer)clearInterval(timer);view.hidden=true;list.hidden=false;document.querySelector('.test-filters').hidden=false;renderList()};document.getElementById('nextQ').onclick=()=>{const selected=view.querySelector('input[name="answer"]:checked');if(!selected){status.textContent='اختر إجابة أولًا.';return}status.textContent='';answers[index]=selected.value;if(answerKey(selected.value)===answerKey(q.answer))score+=Number(q.points)||1;if(index<qs.length-1){index++;renderQ()}else finish()}}
if(remaining){timer=setInterval(()=>{remaining--;const el=document.getElementById('timer');if(el)el.textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0)finish(true)},1000)}renderQ()}
search.addEventListener('input',renderList);subject.addEventListener('change',renderList);branch.addEventListener('change',renderList);getActiveTests().then(r=>{tests=r;fillFilters();status.textContent='';renderList()}).catch(e=>{console.error(e);status.textContent='تعذر تحميل الاختبارات.'});