import { mountShell } from '../components/layout.js';
import { escapeHtml } from '../core/utils.js';
import { getActiveTests, getTest } from '../repositories/testRepository.js';

mountShell('الاختبارات', `<section class="page-head"><span class="eyebrow">مِنهَاج</span><h1>الاختبارات</h1><p>اختبارات مرتبة حسب المحتوى، مع حساب النتيجة فورًا.</p></section><section class="card"><div id="list" class="grid" aria-live="polite"><div class="empty">جاري تحميل الاختبارات...</div></div><div id="status" class="message" role="status"></div></section><section id="testView" class="card" hidden></section>`);
const list=document.getElementById('list'),status=document.getElementById('status'),view=document.getElementById('testView');let tests=[];
function renderList(){list.replaceChildren();if(!tests.length){const e=document.createElement('div');e.className='empty';e.textContent='لا توجد اختبارات منشورة حاليًا.';list.append(e);return}tests.forEach(t=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<span class="eyebrow">اختبار</span><h2>${escapeHtml(t.title||'اختبار')}</h2><p class="muted">${escapeHtml(t.description||'')}</p><p>${(t.questions||[]).length} سؤال${t.durationMinutes?` • ${t.durationMinutes} دقيقة`:''}</p>`;const b=document.createElement('button');b.className='button primary';b.type='button';b.textContent='ابدأ الاختبار';b.onclick=()=>start(t.id);card.append(b);list.append(card)})}
function answerKey(value){const v=String(value||'').trim().toLowerCase();if(v==='صح')return'true';if(v==='خطأ')return'false';return v}
async function start(id){const t=await getTest(id);if(!t){status.textContent='تعذر فتح الاختبار.';return}list.hidden=true;view.hidden=false;let index=0,score=0,answers=[];const qs=Array.isArray(t.questions)?t.questions:[];function renderQ(){const q=qs[index];const options=q.type==='true_false'?['صح','خطأ']:q.options||[];view.innerHTML=`<div class="section-head"><div><span class="eyebrow">السؤال ${index+1} من ${qs.length}</span><h2>${escapeHtml(q.question)}</h2></div><button id="exitTest" class="button" type="button">خروج</button></div><div class="stack">${options.map(o=>`<label class="card" style="display:block;cursor:pointer"><input type="radio" name="answer" value="${escapeHtml(String(o))}" ${answers[index]===String(o)?'checked':''}> ${escapeHtml(String(o))}</label>`).join('')}<div class="actions"><button id="nextQ" class="button primary" type="button">${index===qs.length-1?'إنهاء الاختبار':'التالي'}</button></div></div>`;document.getElementById('exitTest').onclick=()=>{view.hidden=true;list.hidden=false};document.getElementById('nextQ').onclick=()=>{const selected=view.querySelector('input[name="answer"]:checked');if(!selected){status.textContent='اختر إجابة أولًا.';return}answers[index]=selected.value;if(answerKey(selected.value)===answerKey(q.answer))score+=Number(q.points)||1;if(index<qs.length-1){index++;renderQ()}else finish()}}
function finish(){const total=qs.reduce((n,q)=>n+(Number(q.points)||1),0);const percent=total?Math.round(score/total*100):0;view.innerHTML=`<div class="page-head"><span class="eyebrow">انتهى الاختبار</span><h2>نتيجتك: ${score} / ${total}</h2><p>${percent}%</p></div><div class="actions"><button id="retry" class="button primary" type="button">إعادة الاختبار</button><button id="back" class="button" type="button">العودة للاختبارات</button></div>`;document.getElementById('retry').onclick=()=>start(id);document.getElementById('back').onclick=()=>{view.hidden=true;list.hidden=false}}
renderQ()}
getActiveTests().then(r=>{tests=r;status.textContent='';renderList()}).catch(e=>{console.error(e);status.textContent='تعذر تحميل الاختبارات.'});
