import { mountShell } from '../components/layout.js';
import { initStudentAuth, watchAuth, getStudentProfile } from '../services/studentAuth.js';

mountShell('الأدوات', `
<style>
.identity-tools{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px}.identity-tool{padding:24px;border:1px solid #cbd5e1;border-radius:20px;background:linear-gradient(145deg,#fff,#f1f5f9);box-shadow:0 12px 30px rgba(15,23,42,.08)}.identity-tool h2{margin:0 0 8px;color:#0f172a}.identity-tool p{color:#334155;line-height:1.7}.identity-icon{display:grid;place-items:center;width:52px;height:52px;margin-bottom:14px;border-radius:16px;background:#0f172a;color:#fff;font-size:28px;box-shadow:0 8px 18px rgba(15,23,42,.18)}.tool-input{width:100%;box-sizing:border-box;margin:12px 0;padding:13px 15px;border:1px solid #94a3b8;border-radius:12px;background:#fff;color:#0f172a;font:inherit;direction:ltr;text-align:left}.tool-input::placeholder{color:#64748b}.credential-box{display:grid;gap:10px;margin-top:16px}.credential-row{display:grid;gap:5px;padding:12px 14px;border:1px solid #cbd5e1;border-radius:12px;background:#e2e8f0}.credential-label{font-size:12px;color:#475569}.credential-value{font-weight:700;color:#0f172a;word-break:break-all;direction:ltr;text-align:left}.identity-status{margin-top:10px;min-height:22px;font-size:14px;color:#334155}.identity-status.error{color:#991b1b}.identity-status.success{color:#047857;font-weight:600}.tool-note{font-size:13px;margin-top:12px;color:#475569!important}
</style>
<div class="section-head"><div><h1>أدوات الهوية</h1><p>بيانات دخول تعليمية تُنشأ من رقم هوية الطالب.</p></div></div>
<div class="identity-tools">
<article class="card identity-tool"><div class="identity-icon">🎓</div><h2>حساب Microsoft Teams</h2><p>استخدم رقم الهوية لإنشاء البريد وكلمة المرور.</p><label for="teamsIdentity"><strong>رقم الهوية</strong></label><input id="teamsIdentity" class="tool-input" inputmode="numeric" autocomplete="off" placeholder="أدخل رقم الهوية"><button id="teamsGenerate" class="button primary">إنشاء بيانات Teams</button><div id="teamsStatus" class="identity-status"></div><div id="teamsResult" class="credential-box" hidden></div><p class="tool-note">البريد: رقم الهوية@vgaza.edu.ps · كلمة المرور: أول 5 أرقام من الهوية@Gaza</p></article>
<article class="card identity-tool"><div class="identity-icon">🏫</div><h2>حساب iSchool</h2><p>اسم المستخدم وكلمة المرور هما رقم الهوية نفسه.</p><label for="ischoolIdentity"><strong>رقم الهوية</strong></label><input id="ischoolIdentity" class="tool-input" inputmode="numeric" autocomplete="off" placeholder="أدخل رقم الهوية"><button id="ischoolGenerate" class="button primary">إنشاء بيانات iSchool</button><div id="ischoolStatus" class="identity-status"></div><div id="ischoolResult" class="credential-box" hidden></div><p class="tool-note">اسم المستخدم = رقم الهوية · كلمة المرور = رقم الهوية</p></article>
<article class="card" style="padding:24px"><h2>⏱️ مؤقت الدراسة</h2><p id="timer">25:00</p><button id="start" class="button primary">ابدأ</button><button id="reset" class="button">إعادة</button></article>
<article class="card" style="padding:24px"><h2>📝 ملاحظات سريعة</h2><textarea id="notes" placeholder="اكتب ملاحظاتك..."></textarea><button id="save" class="button">حفظ</button></article>
</div>`);

const cleanIdentity=v=>String(v??'').replace(/\s+/g,'').trim();
const validIdentity=v=>/^[0-9]{4,32}$/.test(v);
const escapeHtml=v=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function setup({inputId,buttonId,statusId,resultId,build}){const input=document.getElementById(inputId),button=document.getElementById(buttonId),status=document.getElementById(statusId),result=document.getElementById(resultId);const generate=()=>{const id=cleanIdentity(input.value);result.hidden=true;result.innerHTML='';status.className='identity-status';if(!validIdentity(id)){status.textContent='أدخل رقم هوية صحيحًا يحتوي على أرقام فقط.';status.classList.add('error');return}result.innerHTML=build(id).map(([label,value])=>`<div class="credential-row"><span class="credential-label">${label}</span><span class="credential-value">${escapeHtml(value)}</span></div>`).join('');result.hidden=false;status.textContent='تم إنشاء بيانات الدخول.';status.classList.add('success')};button.onclick=generate;input.onkeydown=e=>{if(e.key==='Enter')generate()};return id=>{if(id&&validIdentity(id)){input.value=id;generate()}}}
const useTeams=setup({inputId:'teamsIdentity',buttonId:'teamsGenerate',statusId:'teamsStatus',resultId:'teamsResult',build:id=>[['البريد الإلكتروني',`${id}@vgaza.edu.ps`],['كلمة المرور',`${id.slice(0,5)}@Gaza`]]});
const useISchool=setup({inputId:'ischoolIdentity',buttonId:'ischoolGenerate',statusId:'ischoolStatus',resultId:'ischoolResult',build:id=>[['اسم المستخدم',id],['كلمة المرور',id]]});
initStudentAuth().catch(()=>{});watchAuth(async user=>{if(!user)return;try{const profile=await getStudentProfile(user.uid);const id=cleanIdentity(profile?.identityNumber);if(id&&validIdentity(id)){useTeams(id);useISchool(id)}}catch(error){console.warn('تعذر تحميل هوية الطالب من الحساب.',error)}});
let seconds=1500,timer=null;const out=document.getElementById('timer');function draw(){out.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}document.getElementById('start').onclick=()=>{if(timer)return;timer=setInterval(()=>{if(seconds<=0){clearInterval(timer);timer=null;return}seconds--;draw()},1000)};document.getElementById('reset').onclick=()=>{clearInterval(timer);timer=null;seconds=1500;draw()};document.getElementById('notes').value=localStorage.getItem('minhaj:notes')||'';document.getElementById('save').onclick=()=>localStorage.setItem('minhaj:notes',document.getElementById('notes').value);draw();
